/** Generated by scripts/build-quiz-index.mjs. Do not edit by hand. */
export const OBJECTIVE_TITLES: Record<string, string> = {
  "SecAI:1.1": "Compare and contrast various AI types and techniques used in cybersecurity",
  "SecAI:1.2": "Explain the importance of data security in relation to AI",
  "SecAI:1.3": "Explain the importance of security throughout the life cycle of AI",
  "SecAI:2.1": "Given a scenario, use AI threat-modeling resources",
  "SecAI:2.2": "Given a set of requirements, implement security controls for AI systems",
  "SecAI:2.3": "Given a scenario, implement appropriate access controls for AI systems",
  "SecAI:2.4": "Given a scenario, implement data security controls for AI systems",
  "SecAI:2.5": "Given a scenario, implement monitoring and auditing for AI systems",
  "SecAI:2.6": "Given a scenario, analyze the evidence of an attack and suggest compensating controls for AI systems",
  "SecAI:3.1": "Given a scenario, use AI-enabled tools to facilitate security tasks",
  "SecAI:3.2": "Explain how AI enables or enhances attack vectors",
  "SecAI:3.3": "Given a scenario, use AI to automate security tasks",
  "SecAI:4.1": "Explain organizational governance structures that support AI",
  "SecAI:4.2": "Explain risks associated with AI",
  "SecAI:4.3": "Summarize the impact of compliance on business use and development of AI"
};
