import type { GlossaryTerm } from '@/types';

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── A ─────────────────────────────────────────────────────────────────────
  {
    term: 'Accuracy',
    definition: 'The proportion of correct predictions made by a model out of all predictions. Calculated as (True Positives + True Negatives) / Total Predictions. Can be misleading on imbalanced datasets where one class dominates.',
    category: 'AI & ML Fundamentals',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Precision', 'Recall', 'F1 Score', 'Confusion Matrix'],
  },
  {
    term: 'Activation Function',
    definition: 'A mathematical function applied to a neuron\'s output to introduce non-linearity into the network, enabling it to learn complex patterns. Common examples include ReLU, sigmoid, tanh, and softmax.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Neural Network', 'ReLU', 'Backpropagation', 'Deep Learning'],
  },
  {
    term: 'Active Learning',
    definition: 'A machine learning paradigm where the model identifies the most informative unlabeled data points and requests human labels for them, reducing labeling cost while maximizing model improvement.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Data Labeling', 'Semi-Supervised Learning', 'Human-in-the-Loop'],
  },
  {
    term: 'Adversarial Attack',
    definition: 'A deliberate manipulation of input data designed to fool an AI model into making incorrect predictions. Examples include adding imperceptible pixel noise to images that causes misclassification, or crafting text that bypasses content filters.',
    category: 'AI Security',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Evasion Attack', 'Model Robustness', 'Adversarial Training', 'OWASP LLM Top 10'],
  },
  {
    term: 'Adversarial Training',
    definition: 'A defense technique that improves model robustness by including adversarial examples in the training data. The model learns to correctly classify both normal and adversarially perturbed inputs.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Adversarial Attack', 'Model Robustness', 'Data Augmentation'],
  },
  {
    term: 'Agent (AI)',
    definition: 'An AI system that autonomously perceives its environment, makes decisions, and takes actions to achieve goals. Agents can use tools, browse the web, write and execute code, and interact with external services.',
    category: 'Emerging Trends',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Agentic AI', 'Tool Use', 'ReAct Pattern', 'LangChain'],
  },
  {
    term: 'Agentic AI',
    definition: 'AI systems that operate autonomously over extended periods, planning multi-step tasks, using tools, and adapting their strategy based on intermediate results without constant human direction.',
    category: 'Emerging Trends',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Agent (AI)', 'Tool Use', 'AutoGPT', 'Multi-Agent System'],
  },
  {
    term: 'Algorithmic Bias',
    definition: 'Systematic and unfair discrimination in AI model outputs stemming from biases in training data, feature selection, or model design. Can perpetuate or amplify existing societal inequalities.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Dataset Bias', 'Fairness', 'Bias Mitigation', 'Responsible AI'],
  },
  {
    term: 'Amazon Bedrock',
    definition: 'AWS\'s fully managed service for accessing foundation models (FMs) from leading AI providers via a single API. Supports model customization via fine-tuning and RAG, with built-in security and compliance features.',
    category: 'Cloud AI Platforms',
    certTags: ['AWS-AIF-C01'],
    related: ['Foundation Model', 'RAG (Retrieval-Augmented Generation)', 'Amazon SageMaker', 'Amazon Q'],
  },
  {
    term: 'Amazon Q',
    definition: 'AWS\'s generative AI-powered assistant for business, available in AWS services and as a standalone business productivity tool. Connects to company data sources to answer questions and automate tasks.',
    category: 'Cloud AI Platforms',
    certTags: ['AWS-AIF-C01'],
    related: ['Amazon Bedrock', 'Amazon SageMaker', 'RAG (Retrieval-Augmented Generation)'],
  },
  {
    term: 'Amazon SageMaker',
    definition: 'AWS\'s fully managed machine learning platform for building, training, and deploying ML models at scale. Provides integrated development environments, automated model tuning, and one-click deployment.',
    category: 'Cloud AI Platforms',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Amazon Bedrock', 'MLOps', 'Model Deployment', 'Feature Store'],
  },
  {
    term: 'Anchor Box',
    definition: 'A predefined bounding box of a specific size and aspect ratio used in object detection models. The model predicts offsets from these anchor boxes rather than predicting absolute coordinates directly.',
    category: 'Computer Vision',
    certTags: ['Google-MLE', 'IBM-AIE'],
    related: ['Object Detection', 'YOLO', 'Intersection over Union (IoU)', 'Non-Maximum Suppression'],
  },
  {
    term: 'Anomaly Detection',
    definition: 'A technique for identifying data points, patterns, or observations that deviate significantly from expected behavior. Used in fraud detection, network intrusion detection, and predictive maintenance.',
    category: 'AI in Security Ops',
    certTags: ['SecAI', 'AWS-AIF-C01', 'GIAC-GASAE'],
    related: ['Behavioral Analytics', 'Unsupervised Learning', 'Isolation Forest', 'AI-Powered SIEM'],
  },
  {
    term: 'AUC-ROC',
    definition: 'Area Under the Receiver Operating Characteristic Curve. A metric measuring a classifier\'s ability to discriminate between classes across all classification thresholds. A value of 1.0 is perfect; 0.5 indicates random guessing.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Google-MLE', 'IBM-AIE'],
    related: ['Precision', 'Recall', 'Confusion Matrix', 'Accuracy'],
  },
  {
    term: 'AutoML',
    definition: 'Automated Machine Learning — tools and techniques that automate the end-to-end process of applying ML, including data preprocessing, feature engineering, model selection, and hyperparameter tuning.',
    category: 'MLOps',
    certTags: ['AWS-AIF-C01', 'Azure-AI102', 'Google-MLE'],
    related: ['Hyperparameter Tuning', 'Feature Engineering', 'Model Selection', 'Vertex AI'],
  },
  {
    term: 'Attention Mechanism',
    definition: 'A component in neural networks that allows the model to focus on the most relevant parts of the input when producing each part of the output. The foundation of transformer architecture, enabling capture of long-range dependencies.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'IBM-AIE'],
    related: ['Transformer', 'Self-Attention', 'Multi-Head Attention', 'BERT'],
  },
  {
    term: 'Azure AI Foundry',
    definition: 'Microsoft\'s unified platform for building and deploying enterprise AI applications, successor to Azure AI Studio. Provides model catalog, prompt flow, evaluation, and deployment capabilities integrated with Azure services.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI102'],
    related: ['Azure OpenAI Service', 'Azure AI Search', 'Azure Machine Learning', 'Prompt Flow'],
  },
  {
    term: 'Azure AI Search',
    definition: 'Microsoft\'s cloud search service that uses AI to extract insights from content at scale. Supports vector search, semantic ranking, and integration with Azure OpenAI for RAG implementations.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI102'],
    related: ['Azure AI Foundry', 'RAG (Retrieval-Augmented Generation)', 'Vector Database', 'Semantic Search'],
  },
  {
    term: 'Azure Machine Learning',
    definition: 'Microsoft\'s cloud ML platform for building, training, and deploying machine learning models. Provides automated ML, designer (low-code), MLflow integration, and managed compute resources.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI900', 'Azure-AI102'],
    related: ['Azure AI Foundry', 'MLOps', 'Amazon SageMaker', 'Vertex AI'],
  },
  {
    term: 'Azure OpenAI Service',
    definition: 'Microsoft\'s Azure-hosted version of OpenAI\'s models (GPT-4, DALL-E, Whisper) with enterprise security, compliance, and regional data residency. Enables RAG, fine-tuning, and agentic workflows in Azure infrastructure.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI102'],
    related: ['Azure AI Foundry', 'Large Language Model (LLM)', 'Fine-Tuning', 'RAG (Retrieval-Augmented Generation)'],
  },
  // ── B ─────────────────────────────────────────────────────────────────────
  {
    term: 'Backdoor Attack',
    definition: 'A training-time attack where an adversary poisons the training data with hidden triggers. The model behaves normally on clean inputs but produces targeted incorrect outputs whenever the trigger pattern is present.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['Data Poisoning', 'Training Data Poisoning', 'Adversarial Attack', 'Model Security'],
  },
  {
    term: 'Backpropagation',
    definition: 'The algorithm for training neural networks by computing the gradient of the loss function with respect to each weight using the chain rule of calculus. Gradients flow backward through the network, enabling weight updates.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Gradient Descent', 'Neural Network', 'Learning Rate', 'Loss Function'],
  },
  {
    term: 'Batch Normalization',
    definition: 'A technique that normalizes the inputs of each layer in a neural network to have zero mean and unit variance within a mini-batch. Accelerates training, allows higher learning rates, and reduces sensitivity to initialization.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Neural Network', 'Deep Learning', 'Training Pipeline', 'Dropout'],
  },
  {
    term: 'Batch Size',
    definition: 'The number of training examples processed together in a single forward/backward pass during model training. Larger batches provide more stable gradient estimates but require more memory; smaller batches introduce noise that can help generalization.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Stochastic Gradient Descent', 'Epoch', 'Learning Rate', 'Gradient Descent'],
  },
  {
    term: 'BERT',
    definition: 'Bidirectional Encoder Representations from Transformers — a pre-trained transformer model that reads text bidirectionally to build deep contextual understanding. Fine-tuned for NLP tasks like classification, NER, and question answering.',
    category: 'NLP',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Transformer', 'GPT', 'Fine-Tuning', 'Attention Mechanism'],
  },
  {
    term: 'Bias (in AI)',
    definition: 'In ML, bias refers to both a model parameter (learned offset) and systematic error (the gap between predicted and true values). Dataset bias refers to training data that does not represent the real-world population fairly.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Algorithmic Bias', 'Variance', 'Overfitting', 'Fairness'],
  },
  {
    term: 'BigQuery ML',
    definition: 'Google Cloud\'s feature that enables training and deploying ML models using standard SQL queries directly in BigQuery. Supports linear regression, logistic regression, k-means, matrix factorization, and imported TensorFlow models.',
    category: 'Cloud AI Platforms',
    certTags: ['Google-MLE'],
    related: ['Vertex AI', 'Google Cloud AI', 'SQL', 'AutoML'],
  },
  {
    term: 'Blue Team',
    definition: 'In security, the team responsible for defending systems against attacks. In AI security, the blue team analyzes AI system defenses, detects adversarial attacks, and implements protective measures against LLM misuse.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GASAE'],
    related: ['Red Team', 'AI Red Team', 'Guardrails', 'Adversarial Attack'],
  },
  // ── C ─────────────────────────────────────────────────────────────────────
  {
    term: 'Chain-of-Thought Prompting',
    definition: 'A prompting technique that encourages LLMs to generate intermediate reasoning steps before reaching a final answer, significantly improving performance on complex reasoning, math, and multi-step tasks.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Prompt Engineering', 'Few-Shot Prompting', 'Zero-Shot Prompting', 'Large Language Model (LLM)'],
  },
  {
    term: 'Class Imbalance',
    definition: 'A condition where the distribution of classes in a dataset is highly unequal, causing models to be biased toward the majority class. Addressed through oversampling, undersampling, SMOTE, or adjusting class weights.',
    category: 'Data Engineering',
    certTags: ['Google-MLE', 'IBM-AIE'],
    related: ['SMOTE', 'Data Augmentation', 'Precision', 'Recall'],
  },
  {
    term: 'Classification',
    definition: 'A supervised learning task where the model predicts a discrete category label for each input. Binary classification has two classes; multiclass has three or more. Common algorithms include logistic regression, decision trees, and SVMs.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Supervised Learning', 'Logistic Regression', 'Decision Tree', 'Regression'],
  },
  {
    term: 'Clustering',
    definition: 'An unsupervised learning task that groups similar data points together without predefined labels. Common algorithms include k-means, hierarchical clustering, and DBSCAN. Used for customer segmentation, anomaly detection, and topic modeling.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900'],
    related: ['Unsupervised Learning', 'K-Means', 'Dimensionality Reduction', 'Feature Engineering'],
  },
  {
    term: 'CNN (Convolutional Neural Network)',
    definition: 'A deep learning architecture designed for processing grid-like data (images, audio). Uses convolutional layers to detect local features (edges, textures), pooling layers for spatial downsampling, and fully connected layers for classification.',
    category: 'Computer Vision',
    certTags: ['AWS-AIF-C01', 'IBM-AIE', 'Google-MLE'],
    related: ['Object Detection', 'Image Classification', 'ResNet', 'Transfer Learning'],
  },
  {
    term: 'Concept Drift',
    definition: 'A change in the statistical relationship between input features and the target variable over time, causing model performance to degrade. Occurs when the real-world distribution shifts after model deployment.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Data Drift', 'Model Drift', 'Model Monitoring', 'Retraining Pipeline'],
  },
  {
    term: 'Conformity Assessment',
    definition: 'Under the EU AI Act, the process by which high-risk AI systems are evaluated against mandatory requirements before market placement. May involve internal checks or third-party notified body review depending on risk category.',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['EU AI Act', 'High-Risk AI System', 'CE Marking (AI Act)', 'ISO 42001'],
  },
  {
    term: 'Confusion Matrix',
    definition: 'A table used to evaluate classifier performance showing the counts of true positives (TP), true negatives (TN), false positives (FP), and false negatives (FN). From this, metrics like accuracy, precision, recall, and F1 score are derived.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Precision', 'Recall', 'F1 Score', 'Accuracy'],
  },
  {
    term: 'Content Filtering',
    definition: 'A safety mechanism that screens AI model inputs and outputs for harmful, inappropriate, or policy-violating content. Can use keyword blocklists, classifiers, or LLM-based judges to detect and block problematic content.',
    category: 'AI Security',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Guardrails', 'OWASP LLM Top 10', 'Prompt Injection', 'LLM02 Insecure Output Handling'],
  },
  {
    term: 'Context Window',
    definition: 'The maximum amount of text (measured in tokens) that an LLM can process in a single interaction, including both the prompt and generated response. Limits how much history, documents, or instructions the model can consider at once.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Token', 'Large Language Model (LLM)', 'Long-Context Window', 'KV Cache'],
  },
  {
    term: 'Coreference Resolution',
    definition: 'An NLP task that identifies when different expressions in text refer to the same real-world entity. For example, resolving "she" to "Alice" in a document — essential for understanding discourse coherence.',
    category: 'NLP',
    certTags: ['IBM-AIE'],
    related: ['Named Entity Recognition (NER)', 'NLP Fundamentals', 'Dependency Parsing'],
  },
  {
    term: 'Cross-Entropy Loss',
    definition: 'A loss function used for classification tasks that measures the difference between the predicted probability distribution and the true label distribution. Lower cross-entropy means the model\'s predicted probabilities are closer to the ground truth.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Loss Function', 'Backpropagation', 'Softmax', 'Classification'],
  },
  {
    term: 'Cross-Validation',
    definition: 'A model evaluation technique that splits data into k folds, training on k-1 folds and testing on the held-out fold repeatedly. K-fold cross-validation gives a more reliable estimate of model performance than a single train/test split.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Overfitting', 'Train/Validation/Test Split', 'Hyperparameter Tuning', 'Model Evaluation'],
  },
  {
    term: 'CUDA',
    definition: 'Compute Unified Device Architecture — NVIDIA\'s parallel computing platform and programming model that enables GPU-accelerated computation. Foundational for deep learning training and inference, supported by PyTorch and TensorFlow.',
    category: 'Frameworks & Tools',
    certTags: ['IBM-AIE'],
    related: ['PyTorch', 'TensorFlow', 'GPU', 'Deep Learning'],
  },
  // ── D ─────────────────────────────────────────────────────────────────────
  {
    term: 'DAN Attack',
    definition: '"Do Anything Now" — a jailbreak technique that instructs an LLM to adopt an unrestricted persona (often named "DAN") that has no safety guidelines. One of the earliest and most widely known jailbreak patterns.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Jailbreak', 'Jailbreak Prompt', 'Role-Play Bypass', 'Prompt Injection'],
  },
  {
    term: 'Data Augmentation',
    definition: 'Techniques for artificially expanding training datasets by creating modified copies of existing data (e.g., flipping images, adding noise, synonym replacement in text). Improves model generalization and reduces overfitting.',
    category: 'Data Engineering',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Training Pipeline', 'Overfitting', 'Class Imbalance', 'Computer Vision'],
  },
  {
    term: 'Data Catalog',
    definition: 'A metadata management system that provides an inventory of data assets in an organization with their descriptions, lineage, quality metrics, and access policies. Enables data discovery and governance at scale.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Data Lineage', 'Data Governance', 'Feature Store', 'Data Quality'],
  },
  {
    term: 'Data Drift',
    definition: 'A change in the statistical properties of model input features over time after deployment. Even if the underlying relationship between features and labels remains stable, drifted input distributions can degrade model performance.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Concept Drift', 'Model Drift', 'Model Monitoring', 'Retraining Pipeline'],
  },
  {
    term: 'Data Labeling',
    definition: 'The process of annotating raw data with ground-truth labels for supervised learning. Can be done manually by human annotators, semi-automatically with model assistance, or automatically with programmatic labeling tools.',
    category: 'Data Engineering',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Active Learning', 'Data Quality', 'Synthetic Data', 'Training Pipeline'],
  },
  {
    term: 'Data Lineage',
    definition: 'The tracking of data\'s origin, transformation history, and movement through a pipeline. Critical for debugging ML models, regulatory compliance, and understanding how training data biases might affect model behavior.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Data Catalog', 'Data Governance', 'Feature Store', 'MLOps'],
  },
  {
    term: 'Data Poisoning',
    definition: 'A training-time attack where an adversary corrupts training data to degrade model performance or introduce backdoors. The corrupted data causes the model to learn incorrect patterns that serve the attacker\'s goals.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['Backdoor Attack', 'Training Data Poisoning', 'Adversarial Attack', 'LLM03 Training Data Poisoning'],
  },
  {
    term: 'Data Quality',
    definition: 'The degree to which data is accurate, complete, consistent, timely, and fit for purpose. Poor data quality is one of the most common reasons ML models fail in production.',
    category: 'Data Engineering',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Data Labeling', 'Data Lineage', 'Feature Engineering', 'Data Augmentation'],
  },
  {
    term: 'Decision Tree',
    definition: 'A supervised learning algorithm that builds a tree of if-then rules by recursively splitting data based on feature values that maximize information gain or minimize impurity. Highly interpretable but prone to overfitting on its own.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Random Forest', 'Gradient Boosting', 'Overfitting', 'Classification'],
  },
  {
    term: 'Deepfake',
    definition: 'Synthetic media (video, audio, image) generated by deep learning models to realistically portray a person doing or saying something they did not do. Poses significant risks to identity fraud, disinformation, and social engineering.',
    category: 'Computer Vision',
    certTags: ['SecAI', 'GIAC-GOAA'],
    related: ['GAN', 'Diffusion Model', 'Phishing & Deepfake Detection', 'Social Engineering'],
  },
  {
    term: 'Deep Learning',
    definition: 'A subset of machine learning that uses neural networks with many layers (deep networks) to automatically learn hierarchical representations from raw data. Responsible for breakthroughs in vision, speech, and language tasks.',
    category: 'AI & ML Fundamentals',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Neural Network', 'Machine Learning', 'Backpropagation', 'CNN (Convolutional Neural Network)'],
  },
  {
    term: 'Demographic Parity',
    definition: 'A fairness criterion requiring that a model\'s positive prediction rate is equal across all demographic groups. Ensures that protected attributes (race, gender, age) do not systematically influence outcomes.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Fairness', 'Equalized Odds', 'Disparate Impact', 'Algorithmic Bias'],
  },
  {
    term: 'Dependency Parsing',
    definition: 'An NLP technique that analyzes the grammatical structure of a sentence by identifying the relationships between words (e.g., subject-verb-object). Produces a dependency tree showing how words are syntactically connected.',
    category: 'NLP',
    certTags: ['IBM-AIE'],
    related: ['NLP Fundamentals', 'Named Entity Recognition (NER)', 'Tokenization'],
  },
  {
    term: 'Differential Privacy',
    definition: 'A mathematical framework for adding calibrated noise to data or model outputs to protect individual privacy while preserving statistical utility. Used in ML to train models on sensitive data without exposing individual records.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Federated Learning', 'Privacy-Preserving AI', 'Model Security', 'GDPR and AI'],
  },
  {
    term: 'Diffusion Model',
    definition: 'A generative AI model that learns to reverse a process of gradually adding noise to data. Trained by learning to denoise, diffusion models can generate highly realistic images (Stable Diffusion, DALL-E 3) and other media.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE'],
    related: ['GAN', 'Generative AI', 'Deepfake', 'Multimodal Model'],
  },
  {
    term: 'Dimensionality Reduction',
    definition: 'Techniques that reduce the number of features in a dataset while preserving important information. Methods include PCA (linear), t-SNE and UMAP (non-linear). Used for visualization, noise reduction, and computational efficiency.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Principal Component Analysis (PCA)', 'Unsupervised Learning', 'Feature Engineering', 'Clustering'],
  },
  {
    term: 'Disparate Impact',
    definition: 'A legal and fairness concept where a neutral AI policy or decision has a disproportionately negative effect on a protected group, even without discriminatory intent. Measured by comparing outcome rates across groups.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Demographic Parity', 'Algorithmic Bias', 'Fairness', 'Responsible AI'],
  },
  {
    term: 'Dropout',
    definition: 'A regularization technique for neural networks that randomly "drops" (sets to zero) a fraction of neurons during each training step. Prevents overfitting by forcing the network to learn redundant representations.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Regularization', 'Overfitting', 'Neural Network', 'Batch Normalization'],
  },
];
