import type { QuizQuestion } from '@/types';

export const QUIZ_QUESTIONS: QuizQuestion[] = [

  // ─── AI & ML Fundamentals ─────────────────────────────────────────────────

  {
    id: 'ml-fund-001',
    topic: 'Supervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'Which type of machine learning uses labeled training data to learn a mapping from inputs to outputs?',
    options: ['Unsupervised learning', 'Reinforcement learning', 'Supervised learning', 'Self-supervised learning'],
    correct: 2,
    explanation: 'Supervised learning trains on labeled (input, output) pairs. The model learns to predict outputs for new inputs based on these examples.',
  },
  {
    id: 'ml-fund-002',
    topic: 'Supervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'What is overfitting in machine learning?',
    options: [
      'The model performs poorly on both training and test data',
      'The model memorizes training data and fails to generalize to new data',
      'The model takes too long to train',
      'The model uses too many features',
    ],
    correct: 1,
    explanation: 'Overfitting occurs when a model learns the training data too well — including noise and specific patterns — making it perform poorly on unseen data.',
  },
  {
    id: 'ml-fund-003',
    topic: 'Supervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'Which technique adds a penalty term to the loss function to reduce model complexity and prevent overfitting?',
    options: ['Data augmentation', 'Regularization', 'Batch normalization', 'Early stopping'],
    correct: 1,
    explanation: 'Regularization (L1/L2) adds a penalty proportional to the magnitude of model weights, discouraging overly complex models that overfit.',
  },
  {
    id: 'ml-fund-004',
    topic: 'Evaluation Metrics',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'A model detects cancer with 95% accuracy on a dataset where 95% of samples are healthy. What is the main problem?',
    options: [
      'The model is overfitting',
      'Accuracy is misleading on imbalanced datasets — the model could predict "healthy" for everything',
      'The training set is too small',
      'The features are not normalized',
    ],
    correct: 1,
    explanation: 'On imbalanced data, a model that always predicts the majority class achieves high accuracy without learning anything useful. Precision/recall/F1 are better metrics.',
  },
  {
    id: 'ml-fund-005',
    topic: 'Evaluation Metrics',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'In a security context, which metric should be prioritized when missing a real threat (false negative) is much more costly than a false alarm?',
    options: ['Precision', 'Recall', 'Specificity', 'Accuracy'],
    correct: 1,
    explanation: 'Recall (= TP / (TP+FN)) measures how many actual positives were caught. High recall minimizes false negatives — critical when missing threats is dangerous.',
  },
  {
    id: 'ml-fund-006',
    topic: 'Evaluation Metrics',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'What does the F1 score represent?',
    options: [
      'The ratio of true positives to total samples',
      'The harmonic mean of precision and recall',
      'The area under the ROC curve',
      'The accuracy on the first evaluation fold',
    ],
    correct: 1,
    explanation: 'F1 = 2 × (Precision × Recall) / (Precision + Recall). It balances both precision and recall in a single metric, useful when both false positives and false negatives matter.',
  },
  {
    id: 'ml-fund-007',
    topic: 'Neural Networks',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI-900'],
    question: 'What is the purpose of an activation function in a neural network?',
    options: [
      'To initialize the model weights',
      'To introduce non-linearity so the network can learn complex patterns',
      'To normalize the input features',
      'To prevent gradient vanishing',
    ],
    correct: 1,
    explanation: 'Without activation functions, a neural network is just a linear transformation regardless of depth. Activation functions introduce non-linearity, enabling the network to learn complex patterns.',
  },
  {
    id: 'ml-fund-008',
    topic: 'Neural Networks',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['AWS-AIF-C01', 'Azure-AI-900'],
    question: 'Which activation function is most commonly used in hidden layers of modern neural networks?',
    options: ['Sigmoid', 'Tanh', 'ReLU', 'Softmax'],
    correct: 2,
    explanation: 'ReLU (Rectified Linear Unit) is the default choice for hidden layers due to its simplicity, computational efficiency, and resistance to the vanishing gradient problem.',
  },
  {
    id: 'ml-fund-009',
    topic: 'Neural Networks',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    question: 'What does backpropagation do in neural network training?',
    options: [
      'Feeds data forward through the network layers',
      'Computes gradients of the loss with respect to weights via the chain rule',
      'Normalizes the batch of training samples',
      'Randomly drops neurons to prevent overfitting',
    ],
    correct: 1,
    explanation: 'Backpropagation uses the chain rule of calculus to compute gradients of the loss function with respect to each weight, enabling gradient-based optimization.',
  },
  {
    id: 'ml-fund-010',
    topic: 'Training Pipeline',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'What is the purpose of a validation set in model training?',
    options: [
      'To provide additional training samples when the training set is small',
      'To tune hyperparameters and evaluate model performance during development',
      'To provide the final unbiased performance estimate',
      'To store the original unprocessed features',
    ],
    correct: 1,
    explanation: 'The validation set is used to tune hyperparameters and make model selection decisions during training. The test set is reserved for the final unbiased evaluation.',
  },
  {
    id: 'ml-fund-011',
    topic: 'Training Pipeline',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['AWS-AIF-C01', 'Azure-AI-900'],
    question: 'What is cross-validation?',
    options: [
      'Training the same model on multiple different datasets',
      'Rotating through different subsets of data as the validation set to get a more reliable performance estimate',
      'Comparing two different models on the same test set',
      'Validating that the model runs on multiple platforms',
    ],
    correct: 1,
    explanation: 'K-fold cross-validation splits data into K folds and trains/evaluates K times, using a different fold as validation each time. This gives a more reliable estimate of generalization performance.',
  },
  {
    id: 'ml-fund-012',
    topic: 'Unsupervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'Which algorithm is most appropriate for detecting unusual network traffic patterns without labeled examples of attacks?',
    options: ['Logistic regression', 'Random forest', 'Isolation Forest', 'Linear regression'],
    correct: 2,
    explanation: 'Isolation Forest is an unsupervised anomaly detection algorithm that isolates anomalies by randomly selecting features and split values. It works without labeled examples of attacks.',
  },
  {
    id: 'ml-fund-013',
    topic: 'Unsupervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    question: 'What is the main advantage of DBSCAN over K-Means clustering?',
    options: [
      'DBSCAN is always faster than K-Means',
      'DBSCAN does not require specifying the number of clusters in advance and can identify outliers',
      'DBSCAN uses less memory than K-Means',
      'DBSCAN works better with high-dimensional data',
    ],
    correct: 1,
    explanation: 'DBSCAN automatically discovers the number of clusters based on density. It also identifies noise points (outliers) that do not belong to any cluster, unlike K-Means.',
  },
  {
    id: 'ml-fund-014',
    topic: 'Neural Networks',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    question: 'What is the purpose of dropout in neural network training?',
    options: [
      'To speed up training by processing fewer neurons',
      'To prevent overfitting by randomly deactivating neurons during training',
      'To reduce the learning rate over time',
      'To initialize weights close to zero',
    ],
    correct: 1,
    explanation: 'Dropout randomly deactivates a fraction of neurons during each training step. This prevents co-adaptation of neurons and acts as an ensemble method, reducing overfitting.',
  },
  {
    id: 'ml-fund-015',
    topic: 'Evaluation Metrics',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'What does an AUC-ROC value of 0.5 indicate?',
    options: [
      'The model has 50% accuracy',
      'The model performs at chance level — no better than random guessing',
      'The model has 50% recall',
      'The model is 50% confident in its predictions',
    ],
    correct: 1,
    explanation: 'AUC-ROC of 0.5 means the model cannot distinguish between positive and negative classes — equivalent to random guessing. AUC of 1.0 is perfect; <0.5 means the model is inverting predictions.',
  },
  {
    id: 'ml-fund-016',
    topic: 'Training Pipeline',
    category: 'AI & ML Fundamentals',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    question: 'What is feature engineering?',
    options: [
      'Designing the neural network architecture',
      'The process of selecting and transforming raw data into informative features for model training',
      'Choosing hyperparameters via grid search',
      'Scaling features to the same range',
    ],
    correct: 1,
    explanation: 'Feature engineering transforms raw data into representations that help the model learn better. It includes creating new features, encoding categoricals, handling missing data, and scaling.',
  },
  {
    id: 'ml-fund-017',
    topic: 'Supervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'advanced',
    certTags: ['Google-MLE'],
    question: 'Which statement correctly describes the bias-variance tradeoff?',
    options: [
      'High bias models have low training error but high test error',
      'High variance models fail on training data but generalize well',
      'High bias means the model is too simple to capture the data structure; high variance means it overfits training data',
      'Increasing model complexity always reduces both bias and variance',
    ],
    correct: 2,
    explanation: 'High bias (underfitting): model is too simple, fails on both train and test. High variance (overfitting): model memorizes training data, fails on test. The goal is to balance both.',
  },
  {
    id: 'ml-fund-018',
    topic: 'Unsupervised Learning',
    category: 'AI & ML Fundamentals',
    difficulty: 'advanced',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    question: 'An autoencoder is trained to reconstruct normal network traffic. At inference, which type of traffic would have the highest reconstruction error?',
    options: [
      'High-volume normal traffic',
      'Traffic similar to the training distribution',
      'Novel anomalous traffic not seen during training',
      'Traffic with longer packet sizes',
    ],
    correct: 2,
    explanation: 'Autoencoders are trained to reconstruct normal data. Anomalous inputs do not match the learned patterns and therefore produce high reconstruction error — making them useful for anomaly detection.',
  },
  {
    id: 'ml-fund-019',
    topic: 'Training Pipeline',
    category: 'AI & ML Fundamentals',
    difficulty: 'advanced',
    certTags: ['Google-MLE'],
    question: 'What is the key difference between hyperparameter tuning and model training?',
    options: [
      'Hyperparameter tuning uses more data than training',
      'Model training optimizes weights given fixed hyperparameters; hyperparameter tuning searches for the best configuration across training runs',
      'Hyperparameter tuning only applies to deep learning',
      'Model training adjusts the architecture; hyperparameter tuning adjusts the data',
    ],
    correct: 1,
    explanation: 'Training optimizes model weights for a fixed hyperparameter configuration. Hyperparameter tuning (grid search, random search, Bayesian optimization) searches the space of configurations to find the best one.',
  },
  {
    id: 'ml-fund-020',
    topic: 'Evaluation Metrics',
    category: 'AI & ML Fundamentals',
    difficulty: 'advanced',
    certTags: ['Google-MLE', 'SecAI'],
    question: 'A fraud detection model has precision=0.90 and recall=0.40. What does this indicate?',
    options: [
      'The model catches most fraud but raises many false alarms',
      'The model rarely triggers alerts, but when it does it is usually correct — however it misses most fraud cases',
      'The model is well-balanced and appropriate for production',
      'The model has poor overall performance and should be retrained',
    ],
    correct: 1,
    explanation: 'High precision (0.90) means 90% of triggered alerts are real fraud — few false alarms. Low recall (0.40) means only 40% of actual fraud is caught — most fraud is missed. This tradeoff may be unacceptable for a fraud system.',
  },


  // ─── Generative AI & LLMs ─────────────────────────────────────────────────

  {
    id: 'genai-001',
    topic: 'Transformer Architecture',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI-900'],
    question: 'What is the primary innovation of the Transformer architecture over RNNs?',
    options: [
      'Transformers use fewer parameters',
      'Transformers process all tokens in parallel using attention instead of sequentially',
      'Transformers require less training data',
      'Transformers only work for text generation',
    ],
    correct: 1,
    explanation: 'Transformers process all tokens in parallel using self-attention, enabling better parallelization and capturing long-range dependencies more effectively than sequential RNNs.',
  },
  {
    id: 'genai-002',
    topic: 'Transformer Architecture',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['AWS-AIF-C01', 'Azure-AI-102'],
    question: 'Which type of transformer model is best suited for text generation tasks like chatbots?',
    options: ['Encoder-only (e.g., BERT)', 'Decoder-only (e.g., GPT)', 'Encoder-Decoder (e.g., T5)', 'Bidirectional encoder'],
    correct: 1,
    explanation: 'Decoder-only models use causal (left-to-right) attention and are optimized for autoregressive text generation. GPT, Claude, and Llama are all decoder-only models.',
  },
  {
    id: 'genai-003',
    topic: 'Prompt Engineering',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01', 'GIAC-GOAA'],
    question: 'What is few-shot prompting?',
    options: [
      'Training a model on a small dataset',
      'Including a small number of input-output examples in the prompt to guide the model',
      'Limiting the model to short responses',
      'Using a subset of the model\'s parameters for inference',
    ],
    correct: 1,
    explanation: 'Few-shot prompting provides 2–5 examples of the desired input-output format within the prompt itself, helping the model understand the expected pattern without fine-tuning.',
  },
  {
    id: 'genai-004',
    topic: 'Prompt Engineering',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01', 'GIAC-GOAA'],
    question: 'Chain-of-thought prompting improves model performance on complex tasks by:',
    options: [
      'Chaining multiple models together',
      'Instructing the model to reason step-by-step before providing an answer',
      'Using the model\'s output as input for the next query',
      'Linking prompts to external knowledge bases',
    ],
    correct: 1,
    explanation: 'Chain-of-thought (CoT) prompting asks the model to articulate its reasoning process step-by-step. This significantly improves accuracy on math, logic, and multi-step reasoning tasks.',
  },
  {
    id: 'genai-005',
    topic: 'RAG',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI-102'],
    question: 'What problem does Retrieval-Augmented Generation (RAG) primarily solve?',
    options: [
      'The model generates text too slowly',
      'The model lacks access to current, private, or domain-specific knowledge not in its training data',
      'The model produces outputs in the wrong format',
      'The model requires too much compute at inference',
    ],
    correct: 1,
    explanation: 'RAG augments LLMs by retrieving relevant documents from a knowledge base before generation, solving the problem of training cutoffs and enabling access to private/real-time data.',
  },
  {
    id: 'genai-006',
    topic: 'RAG',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['SecAI', 'AWS-AIF-C01', 'GIAC-GOAA'],
    question: 'In a RAG pipeline, what is stored in the vector database?',
    options: [
      'The raw text of all documents',
      'The compressed model weights',
      'Numerical vector embeddings representing semantic meaning of document chunks',
      'SQL queries for document retrieval',
    ],
    correct: 2,
    explanation: 'Vector databases store dense vector embeddings — numerical representations of text chunks that capture semantic meaning. At query time, the query is embedded and compared via cosine similarity.',
  },
  {
    id: 'genai-007',
    topic: 'Fine-Tuning',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Azure-AI-102', 'Google-MLE'],
    question: 'What is the main advantage of LoRA over full fine-tuning?',
    options: [
      'LoRA produces higher accuracy on all tasks',
      'LoRA trains only small low-rank adapter matrices, dramatically reducing memory and compute requirements',
      'LoRA does not require any training data',
      'LoRA works only with transformer encoder models',
    ],
    correct: 1,
    explanation: 'LoRA freezes the original model weights and adds small trainable low-rank matrices to attention layers. This reduces trainable parameters to ~0.1-1%, making fine-tuning feasible on consumer hardware.',
  },
  {
    id: 'genai-008',
    topic: 'Fine-Tuning',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    question: 'RLHF is used to align language models to human preferences. What does the "RM" in RLHF training stand for?',
    options: ['Random Model', 'Reward Model', 'Regularization Module', 'Response Monitor'],
    correct: 1,
    explanation: 'RLHF (Reinforcement Learning from Human Feedback) involves training a Reward Model from human preference data (which response is better?), then using RL to optimize the LLM against it.',
  },
  {
    id: 'genai-009',
    topic: 'Transformer Architecture',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Azure-AI-102', 'Google-MLE'],
    question: 'What is the KV cache used for during LLM inference?',
    options: [
      'Storing user conversation history between sessions',
      'Caching key-value attention matrices to avoid recomputing them for previously seen tokens',
      'Key-Value database for storing model outputs',
      'Compressing the model weights for faster loading',
    ],
    correct: 1,
    explanation: 'During autoregressive generation, the KV cache stores the Key and Value matrices for all previously processed tokens, avoiding redundant recomputation and significantly speeding up inference.',
  },
  {
    id: 'genai-010',
    topic: 'Prompt Engineering',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['SecAI', 'AWS-AIF-C01', 'GIAC-GOAA'],
    question: 'What does the "temperature" parameter control in LLM text generation?',
    options: [
      'How fast the model generates tokens',
      'The maximum number of tokens in the output',
      'The randomness/creativity of outputs — higher values make outputs more varied, lower values more deterministic',
      'The model\'s internal compute temperature for stability',
    ],
    correct: 2,
    explanation: 'Temperature scales the logits before softmax sampling. Temperature=0 always picks the most likely token (greedy). Temperature>1 increases randomness. Temperature<1 makes outputs more focused.',
  },
  {
    id: 'genai-011',
    topic: 'RAG',
    category: 'Generative AI & LLMs',
    difficulty: 'advanced',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    question: 'What is an indirect prompt injection attack in the context of a RAG system?',
    options: [
      'An attacker directly modifying the system prompt via the user interface',
      'Malicious instructions embedded in documents that the RAG system retrieves, hijacking the LLM\'s behavior',
      'Injecting extra tokens into the query embedding',
      'Overloading the vector database with adversarial documents',
    ],
    correct: 1,
    explanation: 'Indirect prompt injection (LLM01) occurs when malicious instructions are hidden in external data (web pages, documents) that the RAG system retrieves. The LLM then executes those instructions as if they were legitimate.',
  },
  {
    id: 'genai-012',
    topic: 'Fine-Tuning',
    category: 'Generative AI & LLMs',
    difficulty: 'advanced',
    certTags: ['SecAI', 'CAISP'],
    question: 'During fine-tuning of an LLM, an attacker inserts 100 carefully crafted examples into the training dataset that cause the model to output harmful content when a specific phrase is detected. This is an example of:',
    options: [
      'Model extraction',
      'Adversarial evasion',
      'Backdoor/training data poisoning attack',
      'Membership inference',
    ],
    correct: 2,
    explanation: 'This is a backdoor attack via training data poisoning (OWASP LLM03). The trigger phrase acts as a backdoor — normal inputs cause normal behavior, but the specific trigger activates harmful behavior.',
  },
  {
    id: 'genai-013',
    topic: 'Transformer Architecture',
    category: 'Generative AI & LLMs',
    difficulty: 'advanced',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    question: 'Why does a decoder-only transformer use causal (masked) self-attention?',
    options: [
      'To reduce computation by processing fewer tokens',
      'To prevent each token from attending to future tokens, preserving the autoregressive property',
      'To mask out padding tokens from the loss calculation',
      'To prevent the model from overfitting to training data',
    ],
    correct: 1,
    explanation: 'Causal masking prevents any token from attending to tokens that appear after it in the sequence. This is essential for autoregressive generation — at each step, the model only has access to previously generated tokens.',
  },
  {
    id: 'genai-014',
    topic: 'Prompt Engineering',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    question: 'Which layer of an LLM API prompt defines the model\'s persona, constraints, and rules?',
    options: ['User message', 'Assistant message', 'System prompt', 'Tool result'],
    correct: 2,
    explanation: 'The system prompt sets the model\'s behavior, persona, and constraints. It is processed before the user message and typically contains instructions the application developer wants to enforce.',
  },
  {
    id: 'genai-015',
    topic: 'RAG',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Azure-AI-102'],
    question: 'What is "chunking" in the context of building a RAG system?',
    options: [
      'Compressing the vector database to save storage',
      'Splitting documents into smaller segments before embedding for more precise retrieval',
      'Batching multiple user queries together for efficiency',
      'Breaking model weights into shards for distributed serving',
    ],
    correct: 1,
    explanation: 'Chunking splits large documents into smaller segments (typically 256–1024 tokens) before creating embeddings. This improves retrieval precision — smaller chunks match more specific queries better than entire documents.',
  },
  {
    id: 'genai-016',
    topic: 'Fine-Tuning',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['AWS-AIF-C01'],
    question: 'When should you use RAG instead of fine-tuning to add knowledge to an LLM?',
    options: [
      'When you want the model to adopt a new writing style',
      'When knowledge changes frequently or needs to be kept private and up-to-date',
      'When you need the model to follow a specific output format',
      'When the base model lacks general language understanding',
    ],
    correct: 1,
    explanation: 'RAG is better for dynamic, frequently updated, or private knowledge (no retraining needed). Fine-tuning is better for teaching consistent behavior, tone, or domain-specific reasoning patterns.',
  },
  {
    id: 'genai-017',
    topic: 'Transformer Architecture',
    category: 'Generative AI & LLMs',
    difficulty: 'beginner',
    certTags: ['AWS-AIF-C01', 'Azure-AI-900'],
    question: 'What is "hallucination" in the context of large language models?',
    options: [
      'When the model runs out of context window space',
      'When the model generates confident, plausible-sounding but factually incorrect or fabricated information',
      'When the model repeats the same phrase multiple times',
      'When the model refuses to answer a question',
    ],
    correct: 1,
    explanation: 'Hallucination is when an LLM generates false information presented confidently. It stems from the model\'s probabilistic nature — it predicts plausible text without actually knowing facts. RAG and grounding help reduce it.',
  },
  {
    id: 'genai-018',
    topic: 'Prompt Engineering',
    category: 'Generative AI & LLMs',
    difficulty: 'advanced',
    certTags: ['SecAI', 'GIAC-GOAA'],
    question: 'A developer wants to ensure an LLM returns structured JSON output every time. What is the most reliable approach?',
    options: [
      'Set temperature to 0',
      'Include JSON examples in the system prompt',
      'Use structured output/JSON mode with schema enforcement if available, combined with explicit format instructions',
      'Ask the model politely to use JSON',
    ],
    correct: 2,
    explanation: 'Modern APIs offer structured output modes (JSON mode, response_format with schema) that constrain generation to valid JSON matching a schema. This is more reliable than prompt instructions alone, though both should be used together.',
  },
  {
    id: 'genai-019',
    topic: 'RAG',
    category: 'Generative AI & LLMs',
    difficulty: 'advanced',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    question: 'A RAG knowledge base is populated with internal HR documents. An employee submits a query: "Summarize all documents you retrieved for this response." What risk does this represent?',
    options: [
      'Model denial of service',
      'Training data poisoning',
      'RAG context leakage — sensitive retrieved documents could be disclosed to unauthorized users',
      'Prompt injection via the HR documents',
    ],
    correct: 2,
    explanation: 'If the RAG system retrieves and includes sensitive documents in the context, and users can elicit a summary of that context, they may access documents they shouldn\'t. RAG access controls and output filtering are critical defenses.',
  },
  {
    id: 'genai-020',
    topic: 'Fine-Tuning',
    category: 'Generative AI & LLMs',
    difficulty: 'intermediate',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    question: 'What is DPO (Direct Preference Optimization) and how does it differ from RLHF?',
    options: [
      'DPO uses a separate reward model; RLHF optimizes preferences directly',
      'DPO optimizes preferences directly without training a separate reward model; RLHF requires a reward model and PPO',
      'DPO is for classification tasks; RLHF is for generation',
      'DPO requires more human preference data than RLHF',
    ],
    correct: 1,
    explanation: 'DPO directly optimizes the LLM from human preference pairs without a separate reward model or RL training loop. RLHF trains a reward model first, then uses PPO. DPO is simpler and often more stable.',
  },

];
