import type { GlossaryTerm } from '@/types';

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── A ─────────────────────────────────────────────────────────────────────
  {
    term: 'Accuracy',
    definition: 'The proportion of correct predictions made by a model out of all predictions. Calculated as (True Positives + True Negatives) / Total Predictions. Can be misleading on imbalanced datasets where one class dominates.',
    category: 'AI & ML Fundamentals',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Precision', 'Recall', 'F1 Score', 'Confusion Matrix'],
  },
  {
    term: 'Activation Function',
    definition: 'A mathematical function applied to a neuron\'s output to introduce non-linearity into the network, enabling it to learn complex patterns. Common examples include ReLU, sigmoid, tanh, and softmax.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Neural Network', 'ReLU', 'Backpropagation', 'Deep Learning'],
  },
  {
    term: 'Active Learning',
    definition: 'A machine learning paradigm where the model identifies the most informative unlabeled data points and requests human labels for them, reducing labeling cost while maximizing model improvement.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Data Labeling', 'Semi-Supervised Learning', 'Human-in-the-Loop'],
  },
  {
    term: 'Adversarial Attack',
    definition: 'A deliberate manipulation of input data designed to fool an AI model into making incorrect predictions. Examples include adding imperceptible pixel noise to images that causes misclassification, or crafting text that bypasses content filters.',
    category: 'AI Security',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Evasion Attack', 'Model Robustness', 'Adversarial Training', 'OWASP LLM Top 10'],
  },
  {
    term: 'Adversarial Training',
    definition: 'A defense technique that improves model robustness by including adversarial examples in the training data. The model learns to correctly classify both normal and adversarially perturbed inputs.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Adversarial Attack', 'Model Robustness', 'Data Augmentation'],
  },
  {
    term: 'Agent (AI)',
    definition: 'An AI system that autonomously perceives its environment, makes decisions, and takes actions to achieve goals. Agents can use tools, browse the web, write and execute code, and interact with external services.',
    category: 'Emerging Trends',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Agentic AI', 'Tool Use', 'ReAct Pattern', 'LangChain'],
  },
  {
    term: 'Agentic AI',
    definition: 'AI systems that operate autonomously over extended periods, planning multi-step tasks, using tools, and adapting their strategy based on intermediate results without constant human direction.',
    category: 'Emerging Trends',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Agent (AI)', 'Tool Use', 'AutoGPT', 'Multi-Agent System'],
  },
  {
    term: 'Algorithmic Bias',
    definition: 'Systematic and unfair discrimination in AI model outputs stemming from biases in training data, feature selection, or model design. Can perpetuate or amplify existing societal inequalities.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Dataset Bias', 'Fairness', 'Bias Mitigation', 'Responsible AI'],
  },
  {
    term: 'Amazon Bedrock',
    definition: 'AWS\'s fully managed service for accessing foundation models (FMs) from leading AI providers via a single API. Supports model customization via fine-tuning and RAG, with built-in security and compliance features.',
    category: 'Cloud AI Platforms',
    certTags: ['AWS-AIF-C01'],
    related: ['Foundation Model', 'RAG (Retrieval-Augmented Generation)', 'Amazon SageMaker', 'Amazon Q'],
  },
  {
    term: 'Amazon Q',
    definition: 'AWS\'s generative AI-powered assistant for business, available in AWS services and as a standalone business productivity tool. Connects to company data sources to answer questions and automate tasks.',
    category: 'Cloud AI Platforms',
    certTags: ['AWS-AIF-C01'],
    related: ['Amazon Bedrock', 'Amazon SageMaker', 'RAG (Retrieval-Augmented Generation)'],
  },
  {
    term: 'Amazon SageMaker',
    definition: 'AWS\'s fully managed machine learning platform for building, training, and deploying ML models at scale. Provides integrated development environments, automated model tuning, and one-click deployment.',
    category: 'Cloud AI Platforms',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Amazon Bedrock', 'MLOps', 'Model Deployment', 'Feature Store'],
  },
  {
    term: 'Anchor Box',
    definition: 'A predefined bounding box of a specific size and aspect ratio used in object detection models. The model predicts offsets from these anchor boxes rather than predicting absolute coordinates directly.',
    category: 'Computer Vision',
    certTags: ['Google-MLE', 'IBM-AIE'],
    related: ['Object Detection', 'YOLO', 'Intersection over Union (IoU)', 'Non-Maximum Suppression'],
  },
  {
    term: 'Anomaly Detection',
    definition: 'A technique for identifying data points, patterns, or observations that deviate significantly from expected behavior. Used in fraud detection, network intrusion detection, and predictive maintenance.',
    category: 'AI in Security Ops',
    certTags: ['SecAI', 'AWS-AIF-C01', 'GIAC-GASAE'],
    related: ['Behavioral Analytics', 'Unsupervised Learning', 'Isolation Forest', 'AI-Powered SIEM'],
  },
  {
    term: 'AUC-ROC',
    definition: 'Area Under the Receiver Operating Characteristic Curve. A metric measuring a classifier\'s ability to discriminate between classes across all classification thresholds. A value of 1.0 is perfect; 0.5 indicates random guessing.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Google-MLE', 'IBM-AIE'],
    related: ['Precision', 'Recall', 'Confusion Matrix', 'Accuracy'],
  },
  {
    term: 'AutoML',
    definition: 'Automated Machine Learning — tools and techniques that automate the end-to-end process of applying ML, including data preprocessing, feature engineering, model selection, and hyperparameter tuning.',
    category: 'MLOps',
    certTags: ['AWS-AIF-C01', 'Azure-AI102', 'Google-MLE'],
    related: ['Hyperparameter Tuning', 'Feature Engineering', 'Model Selection', 'Vertex AI'],
  },
  {
    term: 'Attention Mechanism',
    definition: 'A component in neural networks that allows the model to focus on the most relevant parts of the input when producing each part of the output. The foundation of transformer architecture, enabling capture of long-range dependencies.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'IBM-AIE'],
    related: ['Transformer', 'Self-Attention', 'Multi-Head Attention', 'BERT'],
  },
  {
    term: 'Azure AI Foundry',
    definition: 'Microsoft\'s unified platform for building and deploying enterprise AI applications, successor to Azure AI Studio. Provides model catalog, prompt flow, evaluation, and deployment capabilities integrated with Azure services.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI102'],
    related: ['Azure OpenAI Service', 'Azure AI Search', 'Azure Machine Learning', 'Prompt Flow'],
  },
  {
    term: 'Azure AI Search',
    definition: 'Microsoft\'s cloud search service that uses AI to extract insights from content at scale. Supports vector search, semantic ranking, and integration with Azure OpenAI for RAG implementations.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI102'],
    related: ['Azure AI Foundry', 'RAG (Retrieval-Augmented Generation)', 'Vector Database', 'Semantic Search'],
  },
  {
    term: 'Azure Machine Learning',
    definition: 'Microsoft\'s cloud ML platform for building, training, and deploying machine learning models. Provides automated ML, designer (low-code), MLflow integration, and managed compute resources.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI900', 'Azure-AI102'],
    related: ['Azure AI Foundry', 'MLOps', 'Amazon SageMaker', 'Vertex AI'],
  },
  {
    term: 'Azure OpenAI Service',
    definition: 'Microsoft\'s Azure-hosted version of OpenAI\'s models (GPT-4, DALL-E, Whisper) with enterprise security, compliance, and regional data residency. Enables RAG, fine-tuning, and agentic workflows in Azure infrastructure.',
    category: 'Cloud AI Platforms',
    certTags: ['Azure-AI102'],
    related: ['Azure AI Foundry', 'Large Language Model (LLM)', 'Fine-Tuning', 'RAG (Retrieval-Augmented Generation)'],
  },
  // ── B ─────────────────────────────────────────────────────────────────────
  {
    term: 'Backdoor Attack',
    definition: 'A training-time attack where an adversary poisons the training data with hidden triggers. The model behaves normally on clean inputs but produces targeted incorrect outputs whenever the trigger pattern is present.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['Data Poisoning', 'Training Data Poisoning', 'Adversarial Attack', 'Model Security'],
  },
  {
    term: 'Backpropagation',
    definition: 'The algorithm for training neural networks by computing the gradient of the loss function with respect to each weight using the chain rule of calculus. Gradients flow backward through the network, enabling weight updates.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Gradient Descent', 'Neural Network', 'Learning Rate', 'Loss Function'],
  },
  {
    term: 'Batch Normalization',
    definition: 'A technique that normalizes the inputs of each layer in a neural network to have zero mean and unit variance within a mini-batch. Accelerates training, allows higher learning rates, and reduces sensitivity to initialization.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Neural Network', 'Deep Learning', 'Training Pipeline', 'Dropout'],
  },
  {
    term: 'Batch Size',
    definition: 'The number of training examples processed together in a single forward/backward pass during model training. Larger batches provide more stable gradient estimates but require more memory; smaller batches introduce noise that can help generalization.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Stochastic Gradient Descent', 'Epoch', 'Learning Rate', 'Gradient Descent'],
  },
  {
    term: 'BERT',
    definition: 'Bidirectional Encoder Representations from Transformers — a pre-trained transformer model that reads text bidirectionally to build deep contextual understanding. Fine-tuned for NLP tasks like classification, NER, and question answering.',
    category: 'NLP',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Transformer', 'GPT', 'Fine-Tuning', 'Attention Mechanism'],
  },
  {
    term: 'Bias (in AI)',
    definition: 'In ML, bias refers to both a model parameter (learned offset) and systematic error (the gap between predicted and true values). Dataset bias refers to training data that does not represent the real-world population fairly.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Algorithmic Bias', 'Variance', 'Overfitting', 'Fairness'],
  },
  {
    term: 'BigQuery ML',
    definition: 'Google Cloud\'s feature that enables training and deploying ML models using standard SQL queries directly in BigQuery. Supports linear regression, logistic regression, k-means, matrix factorization, and imported TensorFlow models.',
    category: 'Cloud AI Platforms',
    certTags: ['Google-MLE'],
    related: ['Vertex AI', 'Google Cloud AI', 'SQL', 'AutoML'],
  },
  {
    term: 'Blue Team',
    definition: 'In security, the team responsible for defending systems against attacks. In AI security, the blue team analyzes AI system defenses, detects adversarial attacks, and implements protective measures against LLM misuse.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GASAE'],
    related: ['Red Team', 'AI Red Team', 'Guardrails', 'Adversarial Attack'],
  },
  // ── C ─────────────────────────────────────────────────────────────────────
  {
    term: 'Chain-of-Thought Prompting',
    definition: 'A prompting technique that encourages LLMs to generate intermediate reasoning steps before reaching a final answer, significantly improving performance on complex reasoning, math, and multi-step tasks.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Prompt Engineering', 'Few-Shot Prompting', 'Zero-Shot Prompting', 'Large Language Model (LLM)'],
  },
  {
    term: 'Class Imbalance',
    definition: 'A condition where the distribution of classes in a dataset is highly unequal, causing models to be biased toward the majority class. Addressed through oversampling, undersampling, SMOTE, or adjusting class weights.',
    category: 'Data Engineering',
    certTags: ['Google-MLE', 'IBM-AIE'],
    related: ['SMOTE', 'Data Augmentation', 'Precision', 'Recall'],
  },
  {
    term: 'Classification',
    definition: 'A supervised learning task where the model predicts a discrete category label for each input. Binary classification has two classes; multiclass has three or more. Common algorithms include logistic regression, decision trees, and SVMs.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Supervised Learning', 'Logistic Regression', 'Decision Tree', 'Regression'],
  },
  {
    term: 'Clustering',
    definition: 'An unsupervised learning task that groups similar data points together without predefined labels. Common algorithms include k-means, hierarchical clustering, and DBSCAN. Used for customer segmentation, anomaly detection, and topic modeling.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900'],
    related: ['Unsupervised Learning', 'K-Means', 'Dimensionality Reduction', 'Feature Engineering'],
  },
  {
    term: 'CNN (Convolutional Neural Network)',
    definition: 'A deep learning architecture designed for processing grid-like data (images, audio). Uses convolutional layers to detect local features (edges, textures), pooling layers for spatial downsampling, and fully connected layers for classification.',
    category: 'Computer Vision',
    certTags: ['AWS-AIF-C01', 'IBM-AIE', 'Google-MLE'],
    related: ['Object Detection', 'Image Classification', 'ResNet', 'Transfer Learning'],
  },
  {
    term: 'Concept Drift',
    definition: 'A change in the statistical relationship between input features and the target variable over time, causing model performance to degrade. Occurs when the real-world distribution shifts after model deployment.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Data Drift', 'Model Drift', 'Model Monitoring', 'Retraining Pipeline'],
  },
  {
    term: 'Conformity Assessment',
    definition: 'Under the EU AI Act, the process by which high-risk AI systems are evaluated against mandatory requirements before market placement. May involve internal checks or third-party notified body review depending on risk category.',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['EU AI Act', 'High-Risk AI System', 'CE Marking (AI Act)', 'ISO 42001'],
  },
  {
    term: 'Confusion Matrix',
    definition: 'A table used to evaluate classifier performance showing the counts of true positives (TP), true negatives (TN), false positives (FP), and false negatives (FN). From this, metrics like accuracy, precision, recall, and F1 score are derived.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Precision', 'Recall', 'F1 Score', 'Accuracy'],
  },
  {
    term: 'Content Filtering',
    definition: 'A safety mechanism that screens AI model inputs and outputs for harmful, inappropriate, or policy-violating content. Can use keyword blocklists, classifiers, or LLM-based judges to detect and block problematic content.',
    category: 'AI Security',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Guardrails', 'OWASP LLM Top 10', 'Prompt Injection', 'LLM02 Insecure Output Handling'],
  },
  {
    term: 'Context Window',
    definition: 'The maximum amount of text (measured in tokens) that an LLM can process in a single interaction, including both the prompt and generated response. Limits how much history, documents, or instructions the model can consider at once.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Token', 'Large Language Model (LLM)', 'Long-Context Window', 'KV Cache'],
  },
  {
    term: 'Coreference Resolution',
    definition: 'An NLP task that identifies when different expressions in text refer to the same real-world entity. For example, resolving "she" to "Alice" in a document — essential for understanding discourse coherence.',
    category: 'NLP',
    certTags: ['IBM-AIE'],
    related: ['Named Entity Recognition (NER)', 'NLP Fundamentals', 'Dependency Parsing'],
  },
  {
    term: 'Cross-Entropy Loss',
    definition: 'A loss function used for classification tasks that measures the difference between the predicted probability distribution and the true label distribution. Lower cross-entropy means the model\'s predicted probabilities are closer to the ground truth.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Loss Function', 'Backpropagation', 'Softmax', 'Classification'],
  },
  {
    term: 'Cross-Validation',
    definition: 'A model evaluation technique that splits data into k folds, training on k-1 folds and testing on the held-out fold repeatedly. K-fold cross-validation gives a more reliable estimate of model performance than a single train/test split.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Overfitting', 'Train/Validation/Test Split', 'Hyperparameter Tuning', 'Model Evaluation'],
  },
  {
    term: 'CUDA',
    definition: 'Compute Unified Device Architecture — NVIDIA\'s parallel computing platform and programming model that enables GPU-accelerated computation. Foundational for deep learning training and inference, supported by PyTorch and TensorFlow.',
    category: 'Frameworks & Tools',
    certTags: ['IBM-AIE'],
    related: ['PyTorch', 'TensorFlow', 'GPU', 'Deep Learning'],
  },
  // ── D ─────────────────────────────────────────────────────────────────────
  {
    term: 'DAN Attack',
    definition: '"Do Anything Now" — a jailbreak technique that instructs an LLM to adopt an unrestricted persona (often named "DAN") that has no safety guidelines. One of the earliest and most widely known jailbreak patterns.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Jailbreak', 'Jailbreak Prompt', 'Role-Play Bypass', 'Prompt Injection'],
  },
  {
    term: 'Data Augmentation',
    definition: 'Techniques for artificially expanding training datasets by creating modified copies of existing data (e.g., flipping images, adding noise, synonym replacement in text). Improves model generalization and reduces overfitting.',
    category: 'Data Engineering',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Training Pipeline', 'Overfitting', 'Class Imbalance', 'Computer Vision'],
  },
  {
    term: 'Data Catalog',
    definition: 'A metadata management system that provides an inventory of data assets in an organization with their descriptions, lineage, quality metrics, and access policies. Enables data discovery and governance at scale.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Data Lineage', 'Data Governance', 'Feature Store', 'Data Quality'],
  },
  {
    term: 'Data Drift',
    definition: 'A change in the statistical properties of model input features over time after deployment. Even if the underlying relationship between features and labels remains stable, drifted input distributions can degrade model performance.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Concept Drift', 'Model Drift', 'Model Monitoring', 'Retraining Pipeline'],
  },
  {
    term: 'Data Labeling',
    definition: 'The process of annotating raw data with ground-truth labels for supervised learning. Can be done manually by human annotators, semi-automatically with model assistance, or automatically with programmatic labeling tools.',
    category: 'Data Engineering',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Active Learning', 'Data Quality', 'Synthetic Data', 'Training Pipeline'],
  },
  {
    term: 'Data Lineage',
    definition: 'The tracking of data\'s origin, transformation history, and movement through a pipeline. Critical for debugging ML models, regulatory compliance, and understanding how training data biases might affect model behavior.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Data Catalog', 'Data Governance', 'Feature Store', 'MLOps'],
  },
  {
    term: 'Data Poisoning',
    definition: 'A training-time attack where an adversary corrupts training data to degrade model performance or introduce backdoors. The corrupted data causes the model to learn incorrect patterns that serve the attacker\'s goals.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['Backdoor Attack', 'Training Data Poisoning', 'Adversarial Attack', 'LLM03 Training Data Poisoning'],
  },
  {
    term: 'Data Quality',
    definition: 'The degree to which data is accurate, complete, consistent, timely, and fit for purpose. Poor data quality is one of the most common reasons ML models fail in production.',
    category: 'Data Engineering',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Data Labeling', 'Data Lineage', 'Feature Engineering', 'Data Augmentation'],
  },
  {
    term: 'Decision Tree',
    definition: 'A supervised learning algorithm that builds a tree of if-then rules by recursively splitting data based on feature values that maximize information gain or minimize impurity. Highly interpretable but prone to overfitting on its own.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Random Forest', 'Gradient Boosting', 'Overfitting', 'Classification'],
  },
  {
    term: 'Deepfake',
    definition: 'Synthetic media (video, audio, image) generated by deep learning models to realistically portray a person doing or saying something they did not do. Poses significant risks to identity fraud, disinformation, and social engineering.',
    category: 'Computer Vision',
    certTags: ['SecAI', 'GIAC-GOAA'],
    related: ['GAN', 'Diffusion Model', 'Phishing & Deepfake Detection', 'Social Engineering'],
  },
  {
    term: 'Deep Learning',
    definition: 'A subset of machine learning that uses neural networks with many layers (deep networks) to automatically learn hierarchical representations from raw data. Responsible for breakthroughs in vision, speech, and language tasks.',
    category: 'AI & ML Fundamentals',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Neural Network', 'Machine Learning', 'Backpropagation', 'CNN (Convolutional Neural Network)'],
  },
  {
    term: 'Demographic Parity',
    definition: 'A fairness criterion requiring that a model\'s positive prediction rate is equal across all demographic groups. Ensures that protected attributes (race, gender, age) do not systematically influence outcomes.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Fairness', 'Equalized Odds', 'Disparate Impact', 'Algorithmic Bias'],
  },
  {
    term: 'Dependency Parsing',
    definition: 'An NLP technique that analyzes the grammatical structure of a sentence by identifying the relationships between words (e.g., subject-verb-object). Produces a dependency tree showing how words are syntactically connected.',
    category: 'NLP',
    certTags: ['IBM-AIE'],
    related: ['NLP Fundamentals', 'Named Entity Recognition (NER)', 'Tokenization'],
  },
  {
    term: 'Differential Privacy',
    definition: 'A mathematical framework for adding calibrated noise to data or model outputs to protect individual privacy while preserving statistical utility. Used in ML to train models on sensitive data without exposing individual records.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Federated Learning', 'Privacy-Preserving AI', 'Model Security', 'GDPR and AI'],
  },
  {
    term: 'Diffusion Model',
    definition: 'A generative AI model that learns to reverse a process of gradually adding noise to data. Trained by learning to denoise, diffusion models can generate highly realistic images (Stable Diffusion, DALL-E 3) and other media.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE'],
    related: ['GAN', 'Generative AI', 'Deepfake', 'Multimodal Model'],
  },
  {
    term: 'Dimensionality Reduction',
    definition: 'Techniques that reduce the number of features in a dataset while preserving important information. Methods include PCA (linear), t-SNE and UMAP (non-linear). Used for visualization, noise reduction, and computational efficiency.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Principal Component Analysis (PCA)', 'Unsupervised Learning', 'Feature Engineering', 'Clustering'],
  },
  {
    term: 'Disparate Impact',
    definition: 'A legal and fairness concept where a neutral AI policy or decision has a disproportionately negative effect on a protected group, even without discriminatory intent. Measured by comparing outcome rates across groups.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Demographic Parity', 'Algorithmic Bias', 'Fairness', 'Responsible AI'],
  },
  {
    term: 'Dropout',
    definition: 'A regularization technique for neural networks that randomly "drops" (sets to zero) a fraction of neurons during each training step. Prevents overfitting by forcing the network to learn redundant representations.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Regularization', 'Overfitting', 'Neural Network', 'Batch Normalization'],
  },
  // ── E ─────────────────────────────────────────────────────────────────────
  {
    term: 'Embedding',
    definition: 'A dense vector representation of data (text, images, entities) in a continuous high-dimensional space where semantically similar items are close together. Embeddings are the core mechanism enabling semantic search and RAG systems.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Vector Database', 'Semantic Search', 'RAG (Retrieval-Augmented Generation)', 'Tokenization'],
  },
  {
    term: 'Epoch',
    definition: 'One complete pass through the entire training dataset during model training. Multiple epochs are needed for a model to converge; too many epochs cause overfitting, too few cause underfitting.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Batch Size', 'Overfitting', 'Learning Rate', 'Training Pipeline'],
  },
  {
    term: 'Equalized Odds',
    definition: 'A fairness criterion requiring that a classifier has equal true positive rates and equal false positive rates across demographic groups. Stricter than demographic parity, it accounts for both beneficial and harmful decisions.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI'],
    related: ['Demographic Parity', 'Fairness', 'Algorithmic Bias', 'Disparate Impact'],
  },
  {
    term: 'ETL Pipeline',
    definition: 'Extract, Transform, Load — a data engineering pattern for collecting raw data from sources, transforming it (cleaning, aggregating, feature engineering), and loading it into a target store (data warehouse, feature store) for ML use.',
    category: 'Data Engineering',
    certTags: ['Google-MLE'],
    related: ['Feature Store', 'Data Quality', 'Data Lineage', 'MLOps'],
  },
  {
    term: 'EU AI Act',
    definition: 'The European Union\'s comprehensive regulation for artificial intelligence, effective 2024. Classifies AI systems by risk tier (unacceptable, high, limited, minimal) and imposes requirements including transparency, human oversight, and conformity assessments for high-risk systems.',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['NIST AI RMF', 'ISO 42001', 'High-Risk AI System', 'Conformity Assessment'],
  },
  {
    term: 'Evasion Attack',
    definition: 'An adversarial attack that occurs at inference time by manipulating input data to cause model misclassification. Unlike poisoning attacks, the model itself is not modified — only the input is crafted to exploit model weaknesses.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['Adversarial Attack', 'Data Poisoning', 'Model Robustness', 'Adversarial Training'],
  },
  {
    term: 'Excessive Agency',
    definition: 'OWASP LLM08 — a vulnerability where an LLM-based agent is granted too much capability, access, or autonomy, enabling it to take unintended high-impact actions. Mitigated by applying least-privilege principles to agent permissions.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['LLM08 Excessive Agency', 'OWASP LLM Top 10', 'Agentic AI', 'Guardrails'],
  },
  {
    term: 'Explainable AI (XAI)',
    definition: 'Methods and techniques that make AI model decisions understandable to humans. Includes feature importance scores (SHAP, LIME), attention visualization, counterfactual explanations, and inherently interpretable models like decision trees.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['SHAP', 'LIME', 'Model Transparency', 'Responsible AI'],
  },
  // ── F ─────────────────────────────────────────────────────────────────────
  {
    term: 'F1 Score',
    definition: 'The harmonic mean of precision and recall, providing a single metric that balances both. Particularly useful for imbalanced datasets. F1 = 2 × (Precision × Recall) / (Precision + Recall).',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Precision', 'Recall', 'Accuracy', 'Confusion Matrix'],
  },
  {
    term: 'Fairness',
    definition: 'The property of an AI system that does not discriminate against individuals or groups based on protected attributes. Multiple competing mathematical definitions exist (demographic parity, equalized odds, individual fairness) that may be mutually exclusive.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Algorithmic Bias', 'Demographic Parity', 'Equalized Odds', 'Responsible AI'],
  },
  {
    term: 'Federated Learning',
    definition: 'A distributed ML approach where models are trained across multiple devices or servers holding local data, without the data ever leaving its source. The server aggregates only model updates (gradients), preserving privacy.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Differential Privacy', 'Privacy-Preserving AI', 'Data Governance', 'Model Security'],
  },
  {
    term: 'Feature Engineering',
    definition: 'The process of using domain knowledge to create, transform, or select input features that improve model performance. Includes normalization, encoding categorical variables, creating interaction terms, and binning continuous variables.',
    category: 'Data Engineering',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Feature Selection', 'Feature Store', 'Data Quality', 'Dimensionality Reduction'],
  },
  {
    term: 'Feature Selection',
    definition: 'The process of identifying and retaining only the most informative features for model training. Reduces dimensionality, improves model interpretability, decreases training time, and can improve generalization.',
    category: 'Data Engineering',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Feature Engineering', 'Dimensionality Reduction', 'Principal Component Analysis (PCA)', 'Overfitting'],
  },
  {
    term: 'Feature Store',
    definition: 'A centralized repository that stores, manages, and serves computed feature values for ML models. Provides consistent features across training and inference, enabling feature reuse and reducing duplication across teams.',
    category: 'MLOps',
    certTags: ['Google-MLE'],
    related: ['ETL Pipeline', 'MLOps', 'Model Deployment', 'Data Lineage'],
  },
  {
    term: 'Few-Shot Prompting',
    definition: 'A prompting technique that provides a small number of input-output examples in the prompt to demonstrate the desired task format or behavior to an LLM, without updating model weights.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Zero-Shot Prompting', 'Chain-of-Thought Prompting', 'Prompt Engineering', 'In-Context Learning'],
  },
  {
    term: 'Fine-Tuning',
    definition: 'Adapting a pre-trained model to a specific task or domain by continuing training on a smaller, task-specific dataset. Updates some or all model weights. More expensive than prompting but produces better task-specific performance.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102', 'IBM-AIE'],
    related: ['Pre-Training', 'PEFT', 'LoRA', 'Transfer Learning'],
  },
  {
    term: 'Foundation Model',
    definition: 'A large AI model trained on broad data that can be adapted to a wide range of downstream tasks. Examples include GPT-4, Claude, Llama, and Gemini. Foundation models are the base for most modern LLM applications.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Large Language Model (LLM)', 'Fine-Tuning', 'Pre-Training', 'Amazon Bedrock'],
  },
  // ── G ─────────────────────────────────────────────────────────────────────
  {
    term: 'GAN (Generative Adversarial Network)',
    definition: 'A generative model architecture consisting of two neural networks — a generator that creates synthetic data and a discriminator that tries to distinguish real from fake. The two networks train in opposition, improving each other iteratively.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Diffusion Model', 'Deepfake', 'Generative AI', 'Synthetic Data'],
  },
  {
    term: 'GDPR and AI',
    definition: 'The EU\'s General Data Protection Regulation applies to AI systems processing personal data. Key requirements include lawful basis for processing, data minimization, right to explanation for automated decisions, and data subject rights.',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['EU AI Act', 'Responsible AI', 'Differential Privacy', 'Privacy-Preserving AI'],
  },
  {
    term: 'Goal Hijacking',
    definition: 'A prompt injection attack where an adversary embeds instructions in content the LLM processes (emails, documents, web pages) to override the model\'s intended objective and redirect its actions toward the attacker\'s goal.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Indirect Prompt Injection', 'Prompt Injection', 'LLM01 Prompt Injection', 'Adversarial Prompt'],
  },
  {
    term: 'Gradient Boosting',
    definition: 'An ensemble learning technique that builds models sequentially, each new model correcting the errors of the previous one by fitting to residuals. XGBoost, LightGBM, and CatBoost are highly optimized gradient boosting implementations.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Random Forest', 'Decision Tree', 'XGBoost', 'Ensemble Learning'],
  },
  {
    term: 'Gradient Descent',
    definition: 'An optimization algorithm that iteratively updates model parameters in the direction of the negative gradient of the loss function. Forms the basis of neural network training; variants include SGD, Adam, and RMSprop.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Backpropagation', 'Learning Rate', 'Stochastic Gradient Descent', 'Loss Function'],
  },
  {
    term: 'Grounding',
    definition: 'Connecting an LLM\'s responses to verified external sources (documents, databases, APIs) to reduce hallucination and ensure factual accuracy. RAG is the primary grounding technique; tool use and citations also serve this purpose.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['RAG (Retrieval-Augmented Generation)', 'Hallucination', 'Vector Database', 'Tool Use'],
  },
  {
    term: 'Guardrails',
    definition: 'Safety mechanisms applied to AI systems to constrain inputs and outputs within acceptable boundaries. Include content filters, topic classifiers, PII detectors, rate limiters, and prompt injection shields.',
    category: 'AI Security',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102', 'CAISP'],
    related: ['Content Filtering', 'OWASP LLM Top 10', 'Prompt Injection', 'LLM01 Prompt Injection'],
  },
  // ── H ─────────────────────────────────────────────────────────────────────
  {
    term: 'Hallucination',
    definition: 'When an LLM generates confident-sounding but factually incorrect, fabricated, or inconsistent information. Caused by training on imperfect data and the probabilistic nature of token prediction. Mitigated by grounding and RAG.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Grounding', 'RAG (Retrieval-Augmented Generation)', 'Large Language Model (LLM)', 'Prompt Engineering'],
  },
  {
    term: 'High-Risk AI System',
    definition: 'Under the EU AI Act, AI systems that pose significant risks to health, safety, or fundamental rights — including biometric identification, critical infrastructure, employment decisions, and law enforcement applications. Subject to strict requirements.',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['EU AI Act', 'Conformity Assessment', 'AI Risk Management', 'CE Marking (AI Act)'],
  },
  {
    term: 'Human-in-the-Loop',
    definition: 'A design pattern where human judgment is incorporated at key decision points in an AI pipeline. Can involve human labeling, verification of model outputs, or final approval before automated actions are taken.',
    category: 'AI Governance',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Active Learning', 'Responsible AI', 'AI Risk Management', 'Excessive Agency'],
  },
  {
    term: 'Hyperparameter Tuning',
    definition: 'The process of finding optimal hyperparameters (settings that control the learning process, not learned from data) such as learning rate, batch size, and number of layers. Methods include grid search, random search, and Bayesian optimization.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Google-MLE', 'IBM-AIE'],
    related: ['Cross-Validation', 'AutoML', 'Learning Rate', 'Overfitting'],
  },
  {
    term: 'Hugging Face',
    definition: 'An AI platform and open-source community providing the Transformers library, model Hub, and Datasets library. The de facto standard for accessing pre-trained NLP models, fine-tuning LLMs, and sharing ML artifacts.',
    category: 'Frameworks & Tools',
    certTags: ['IBM-AIE'],
    related: ['Transformers Library', 'Fine-Tuning', 'PEFT', 'LangChain'],
  },
  // ── I ─────────────────────────────────────────────────────────────────────
  {
    term: 'Image Classification',
    definition: 'A computer vision task that assigns a single label to an entire image. Foundational CV task solved by CNNs; modern approaches use pre-trained ResNet, EfficientNet, or Vision Transformer (ViT) models with transfer learning.',
    category: 'Computer Vision',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['CNN (Convolutional Neural Network)', 'Object Detection', 'Transfer Learning', 'ResNet'],
  },
  {
    term: 'In-Context Learning',
    definition: 'The ability of LLMs to adapt their behavior based on examples or instructions provided in the prompt, without any weight updates. Enables few-shot and zero-shot task performance by leveraging the model\'s pattern recognition.',
    category: 'Generative AI & LLMs',
    certTags: ['AWS-AIF-C01'],
    related: ['Few-Shot Prompting', 'Zero-Shot Prompting', 'Prompt Engineering', 'Foundation Model'],
  },
  {
    term: 'Indirect Prompt Injection',
    definition: 'A prompt injection attack where malicious instructions are embedded in external content (documents, emails, web pages) that the LLM retrieves or processes, allowing attackers to hijack the model\'s behavior without direct user interaction.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Prompt Injection', 'Goal Hijacking', 'RAG Injection', 'LLM01 Prompt Injection'],
  },
  {
    term: 'Inference',
    definition: 'The process of using a trained ML model to make predictions on new, unseen data. Inference performance (latency, throughput, cost) is a key concern in production deployments, distinct from training performance.',
    category: 'MLOps',
    certTags: ['AWS-AIF-C01', 'Azure-AI102', 'Google-MLE'],
    related: ['Model Deployment', 'Model Serving', 'KV Cache', 'Quantization'],
  },
  {
    term: 'Instruction Tuning',
    definition: 'Fine-tuning an LLM on a dataset of (instruction, output) pairs to improve its ability to follow natural language instructions. Transforms a base language model into a helpful assistant that responds appropriately to user requests.',
    category: 'Generative AI & LLMs',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Fine-Tuning', 'RLHF', 'Prompt Engineering', 'Foundation Model'],
  },
  {
    term: 'Intersection over Union (IoU)',
    definition: 'A metric for evaluating object detection accuracy that measures the overlap between the predicted bounding box and the ground-truth bounding box. IoU = Area of Overlap / Area of Union. Typical threshold is 0.5.',
    category: 'Computer Vision',
    certTags: ['IBM-AIE'],
    related: ['Object Detection', 'YOLO', 'Anchor Box', 'Non-Maximum Suppression'],
  },
  {
    term: 'IOC (Indicator of Compromise)',
    definition: 'Evidence that a system has been compromised — including malicious IP addresses, domain names, file hashes, and behavioral patterns. AI-powered SOC tools automate IOC extraction from logs, alerts, and incident data.',
    category: 'AI in Security Ops',
    certTags: ['SecAI', 'GIAC-GASAE'],
    related: ['Alert Enrichment', 'MITRE ATT&CK', 'Threat Intelligence', 'AI-Powered SIEM'],
  },
  {
    term: 'ISO 42001',
    definition: 'The international standard for AI Management Systems (AIMS), published in 2023. Provides a framework for organizations to govern AI development and use responsibly, covering risk management, transparency, and continual improvement.',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['NIST AI RMF', 'EU AI Act', 'Responsible AI', 'AI Risk Management'],
  },
  // ── J ─────────────────────────────────────────────────────────────────────
  {
    term: 'Jailbreak',
    definition: 'An attack technique that manipulates an LLM into bypassing its safety training and producing content it was designed to refuse. Methods include role-play scenarios, hypothetical framing, DAN prompts, and multi-turn manipulation.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['DAN Attack', 'Role-Play Bypass', 'Prompt Injection', 'Guardrails'],
  },
  {
    term: 'Jailbreak Prompt',
    definition: 'A specific input crafted to bypass an LLM\'s safety guardrails. Examples include telling the model it is in "developer mode", framing harmful requests as fiction, or using character encoding to obscure intent.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA'],
    related: ['Jailbreak', 'DAN Attack', 'Adversarial Prompt', 'Guardrails'],
  },
  // ── K ─────────────────────────────────────────────────────────────────────
  {
    term: 'K-Nearest Neighbors (KNN)',
    definition: 'A simple, instance-based learning algorithm that classifies a new data point by majority vote of its k nearest training examples in feature space. No training phase; all computation is at inference time.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Classification', 'Clustering', 'Supervised Learning', 'Feature Engineering'],
  },
  {
    term: 'Keras',
    definition: 'A high-level deep learning API written in Python, now integrated into TensorFlow as tf.keras. Provides a user-friendly interface for building and training neural networks with minimal boilerplate code.',
    category: 'Frameworks & Tools',
    certTags: ['IBM-AIE'],
    related: ['TensorFlow', 'PyTorch', 'Neural Network', 'Deep Learning'],
  },
  {
    term: 'KV Cache',
    definition: 'Key-Value cache — an optimization in transformer inference that stores previously computed attention keys and values to avoid redundant computation when generating each new token. Dramatically reduces inference latency for long sequences.',
    category: 'Generative AI & LLMs',
    certTags: ['Google-MLE'],
    related: ['Transformer', 'Inference', 'Context Window', 'Speculative Decoding'],
  },
  // ── L ─────────────────────────────────────────────────────────────────────
  {
    term: 'LangChain',
    definition: 'An open-source framework for building LLM-powered applications. Provides abstractions for chains, agents, memory, and tool integrations, making it easier to build RAG systems, chatbots, and autonomous agents.',
    category: 'Frameworks & Tools',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['RAG (Retrieval-Augmented Generation)', 'Agent (AI)', 'LlamaIndex', 'Tool Use'],
  },
  {
    term: 'Large Language Model (LLM)',
    definition: 'A neural network trained on massive text corpora to predict and generate human-like text. Modern LLMs (GPT-4, Claude, Gemini, Llama) have billions of parameters and exhibit emergent capabilities like reasoning and code generation.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Foundation Model', 'Transformer', 'Prompt Engineering', 'Hallucination'],
  },
  {
    term: 'Learning Rate',
    definition: 'A hyperparameter controlling how much model weights are updated in response to the gradient during each training step. Too high causes divergence; too low causes slow convergence or getting stuck in local minima.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Gradient Descent', 'Backpropagation', 'Hyperparameter Tuning', 'Epoch'],
  },
  {
    term: 'LIME',
    definition: 'Local Interpretable Model-agnostic Explanations — an XAI technique that explains individual model predictions by fitting a locally linear model around a specific input instance, revealing which features most influenced that prediction.',
    category: 'AI Ethics & Bias',
    certTags: ['SecAI', 'Google-MLE'],
    related: ['SHAP', 'Explainable AI (XAI)', 'Model Transparency', 'Feature Engineering'],
  },
  {
    term: 'LlamaIndex',
    definition: 'An open-source data framework for building LLM applications over custom data. Provides tools for data ingestion, indexing, querying, and retrieval — the primary alternative to LangChain for RAG and knowledge base applications.',
    category: 'Frameworks & Tools',
    certTags: ['AWS-AIF-C01'],
    related: ['LangChain', 'RAG (Retrieval-Augmented Generation)', 'Vector Database', 'Agent (AI)'],
  },
  {
    term: 'LLM01 Prompt Injection',
    definition: 'OWASP LLM Top 10 #1 — an attack where adversarial inputs manipulate an LLM into executing unintended actions, overriding its instructions, or leaking sensitive information. The most prevalent LLM vulnerability.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['Prompt Injection', 'OWASP LLM Top 10', 'Indirect Prompt Injection', 'Guardrails'],
  },
  {
    term: 'LLM02 Insecure Output Handling',
    definition: 'OWASP LLM Top 10 #2 — failure to properly validate or sanitize LLM outputs before passing them to downstream systems. Can lead to XSS, SSRF, SQL injection, or remote code execution if model outputs are used in web pages or system calls.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'Content Filtering', 'Guardrails', 'LLM01 Prompt Injection'],
  },
  {
    term: 'LLM03 Training Data Poisoning',
    definition: 'OWASP LLM Top 10 #3 — manipulating training or fine-tuning data to introduce backdoors, biases, or vulnerabilities into the model. Particularly concerning for models trained on internet-scraped data or third-party datasets.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'Data Poisoning', 'Backdoor Attack', 'AI Supply Chain'],
  },
  {
    term: 'LLM04 Model Denial of Service',
    definition: 'OWASP LLM Top 10 #4 — attacks that cause an LLM to consume excessive resources (compute, memory, API calls) through carefully crafted inputs, degrading service availability for other users.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'Rate Limiting', 'Guardrails', 'LLM Service Security'],
  },
  {
    term: 'LLM05 Supply Chain Vulnerabilities',
    definition: 'OWASP LLM Top 10 #5 — risks from third-party dependencies in the LLM supply chain, including pre-trained models, datasets, plugins, and infrastructure components that may contain vulnerabilities or malicious code.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'AI Supply Chain', 'LLM03 Training Data Poisoning', 'Model Security'],
  },
  {
    term: 'LLM06 Sensitive Information Disclosure',
    definition: 'OWASP LLM Top 10 #6 — unintended leakage of confidential data (PII, credentials, system prompts, proprietary information) in model responses due to inadequate output filtering or training data memorization.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'Prompt Leaking', 'System Prompt Extraction', 'Data Exfiltration via LLM'],
  },
  {
    term: 'LLM07 Insecure Plugin Design',
    definition: 'OWASP LLM Top 10 #7 — vulnerabilities arising from LLM plugins and tools with insufficient input validation, excessive permissions, or improper authorization, allowing attackers to misuse plugin capabilities.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'Tool Use', 'Excessive Agency', 'LLM08 Excessive Agency'],
  },
  {
    term: 'LLM08 Excessive Agency',
    definition: 'OWASP LLM Top 10 #8 — granting an LLM-based system more permissions, capabilities, or autonomy than needed, enabling unintended high-impact actions if the model is manipulated or makes errors.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['OWASP LLM Top 10', 'Excessive Agency', 'Agentic AI', 'LLM07 Insecure Plugin Design'],
  },
  {
    term: 'Logistic Regression',
    definition: 'A supervised classification algorithm that models the probability of a binary outcome using the logistic (sigmoid) function. Despite the name, it is a classification algorithm, not regression. Highly interpretable and widely used as a baseline.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Classification', 'Supervised Learning', 'Decision Tree', 'Linear Regression'],
  },
  {
    term: 'Long-Context Window',
    definition: 'LLMs with context windows of 128K tokens or more, enabling processing of entire books, codebases, or meeting transcripts in a single inference call. Reduces the need for chunking strategies in RAG but increases compute cost.',
    category: 'Emerging Trends',
    certTags: ['AWS-AIF-C01'],
    related: ['Context Window', 'RAG (Retrieval-Augmented Generation)', 'KV Cache', 'Large Language Model (LLM)'],
  },
  {
    term: 'LoRA (Low-Rank Adaptation)',
    definition: 'A parameter-efficient fine-tuning (PEFT) technique that injects trainable low-rank matrices into transformer layers rather than updating all parameters. Reduces memory footprint by 10-100x while achieving near full fine-tuning performance.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['PEFT', 'QLoRA', 'Fine-Tuning', 'Transformer'],
  },
  {
    term: 'Loss Function',
    definition: 'A mathematical function that measures the difference between a model\'s predictions and the true labels. The model\'s weights are updated to minimize this function during training. Common examples: MSE (regression), cross-entropy (classification).',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['Gradient Descent', 'Backpropagation', 'Cross-Entropy Loss', 'Training Pipeline'],
  },
  // ── M ─────────────────────────────────────────────────────────────────────
  {
    term: 'Machine Learning',
    definition: 'A subset of AI where systems learn patterns from data to make predictions or decisions without explicit rule programming. Encompasses supervised, unsupervised, and reinforcement learning paradigms.',
    category: 'AI & ML Fundamentals',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Deep Learning', 'Supervised Learning', 'Unsupervised Learning', 'Neural Network'],
  },
  {
    term: 'Membership Inference Attack',
    definition: 'A privacy attack that determines whether a specific data point was included in a model\'s training set. Exploits the tendency of models to behave differently on training data vs. unseen data, exposing sensitive training records.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Differential Privacy', 'Federated Learning', 'Model Extraction', 'Data Poisoning'],
  },
  {
    term: 'MITRE ATLAS',
    definition: 'Adversarial Threat Landscape for Artificial-Intelligence Systems — a knowledge base of adversarial ML tactics and techniques modeled after MITRE ATT&CK. Maps AI-specific attacks like model evasion, data poisoning, and model extraction.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['MITRE ATT&CK', 'Adversarial Attack', 'AI Red Team', 'OWASP LLM Top 10'],
  },
  {
    term: 'MITRE ATT&CK',
    definition: 'A globally-accessible knowledge base of adversary tactics, techniques, and procedures (TTPs) based on real-world observations. Used in AI security ops for alert enrichment, detection rule development, and incident response.',
    category: 'AI in Security Ops',
    certTags: ['SecAI', 'GIAC-GASAE'],
    related: ['MITRE ATLAS', 'IOC (Indicator of Compromise)', 'Detection Rule', 'Threat Intelligence'],
  },
  {
    term: 'MLflow',
    definition: 'An open-source MLOps platform for experiment tracking, model registry, and model serving. Provides a UI and API for logging parameters, metrics, and artifacts; natively integrated into Databricks and Azure ML.',
    category: 'Frameworks & Tools',
    certTags: ['Google-MLE'],
    related: ['MLOps', 'Experiment Tracking', 'Model Registry', 'Weights & Biases'],
  },
  {
    term: 'MLOps',
    definition: 'Machine Learning Operations — the practice of applying DevOps principles to ML systems. Encompasses the full ML lifecycle: data management, model training, evaluation, deployment, monitoring, and retraining automation.',
    category: 'MLOps',
    certTags: ['AWS-AIF-C01', 'Azure-AI102', 'Google-MLE'],
    related: ['Model Deployment', 'Model Monitoring', 'Feature Store', 'CI/CD for ML'],
  },
  {
    term: 'Model Card',
    definition: 'A documentation artifact that describes a trained ML model\'s intended uses, performance across demographic groups, limitations, and ethical considerations. Introduced by Google to promote model transparency and responsible deployment.',
    category: 'AI Governance',
    certTags: ['SecAI', 'AWS-AIF-C01'],
    related: ['Responsible AI', 'Transparency', 'Explainable AI (XAI)', 'AI Risk Management'],
  },
  {
    term: 'Model Deployment',
    definition: 'Making a trained ML model available for inference in production. Strategies include batch inference, real-time REST APIs, streaming predictions, edge deployment, and serverless functions.',
    category: 'MLOps',
    certTags: ['AWS-AIF-C01', 'Azure-AI102', 'Google-MLE'],
    related: ['Model Serving', 'Inference', 'Blue-Green Deployment', 'Canary Deployment'],
  },
  {
    term: 'Model Drift',
    definition: 'A general term for any degradation of model performance over time in production. Encompasses data drift (input distribution changes) and concept drift (relationship between inputs and outputs changes).',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Data Drift', 'Concept Drift', 'Model Monitoring', 'Retraining Pipeline'],
  },
  {
    term: 'Model Evaluation',
    definition: 'The process of assessing a trained model\'s performance using metrics appropriate for the task type. Includes offline evaluation on held-out test sets, A/B testing in production, and human evaluation for generative models.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Google-MLE'],
    related: ['Confusion Matrix', 'Cross-Validation', 'AUC-ROC', 'F1 Score'],
  },
  {
    term: 'Model Extraction',
    definition: 'An attack that reverse-engineers a proprietary ML model by querying it with carefully crafted inputs and using the responses to train a surrogate model. Enables competitors to steal model functionality without access to training data or weights.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Membership Inference Attack', 'Adversarial Attack', 'Model Security', 'LLM05 Supply Chain Vulnerabilities'],
  },
  {
    term: 'Model Inversion',
    definition: 'An attack that reconstructs training data or sensitive attributes from a model\'s outputs. By repeatedly querying the model with optimized inputs, attackers can reconstruct images of individuals from face recognition systems.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP'],
    related: ['Membership Inference Attack', 'Differential Privacy', 'Federated Learning', 'Model Security'],
  },
  {
    term: 'Model Monitoring',
    definition: 'Continuously tracking model performance, data distributions, and system health in production. Detects data drift, concept drift, and performance degradation to trigger alerts or automated retraining.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Data Drift', 'Concept Drift', 'Model Drift', 'Retraining Pipeline'],
  },
  {
    term: 'Model Registry',
    definition: 'A centralized repository for versioning, storing, and managing ML model artifacts throughout their lifecycle. Tracks model versions, associated metadata, performance metrics, and deployment status.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'Azure-AI102'],
    related: ['MLOps', 'Model Versioning', 'MLflow', 'CI/CD for ML'],
  },
  {
    term: 'Model Serving',
    definition: 'The infrastructure layer that handles inference requests in production: receiving input, running the model, and returning predictions. Frameworks include TorchServe, TensorFlow Serving, NVIDIA Triton, and managed services.',
    category: 'MLOps',
    certTags: ['Google-MLE', 'AWS-AIF-C01'],
    related: ['Inference', 'Model Deployment', 'Triton Inference Server', 'Containerization'],
  },
  {
    term: 'Multi-Agent System',
    definition: 'An architecture where multiple AI agents collaborate or compete to solve problems too complex for a single agent. Agents can specialize in different tasks, check each other\'s work, or operate in parallel pipelines.',
    category: 'Emerging Trends',
    certTags: ['AWS-AIF-C01', 'Azure-AI102'],
    related: ['Agentic AI', 'Agent (AI)', 'Tool Use', 'LangChain'],
  },
  {
    term: 'Multi-Head Attention',
    definition: 'An extension of attention that runs multiple attention operations ("heads") in parallel on different linear projections of the input. Each head can attend to different aspects of the input, improving representation richness.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE'],
    related: ['Attention Mechanism', 'Self-Attention', 'Transformer', 'BERT'],
  },
  {
    term: 'Multimodal Model',
    definition: 'An AI model that can process and generate multiple data types — combining text, images, audio, and video in a single architecture. Examples include GPT-4o, Gemini, and Claude 3, which accept both text and image inputs.',
    category: 'Generative AI & LLMs',
    certTags: ['AWS-AIF-C01', 'Azure-AI102'],
    related: ['Vision-Language Model', 'Foundation Model', 'Large Language Model (LLM)', 'Diffusion Model'],
  },
  {
    term: 'Mixture of Experts (MoE)',
    definition: 'A neural network architecture where only a subset of the model\'s parameters (expert networks) are activated for each input, selected by a routing mechanism. Enables very large models while keeping inference cost manageable.',
    category: 'Emerging Trends',
    certTags: ['Google-MLE'],
    related: ['Foundation Model', 'Large Language Model (LLM)', 'Speculative Decoding', 'Inference'],
  },
  // ── N ─────────────────────────────────────────────────────────────────────
  {
    term: 'Named Entity Recognition (NER)',
    definition: 'An NLP task that identifies and classifies named entities in text into categories such as person, organization, location, date, and product. Used in information extraction, knowledge graph construction, and alert enrichment.',
    category: 'NLP',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['NLP Fundamentals', 'Sentiment Analysis', 'Text Classification', 'IOC (Indicator of Compromise)'],
  },
  {
    term: 'Neural Network',
    definition: 'A computational model inspired by biological neurons, consisting of layers of interconnected nodes that transform input data through weighted connections and activation functions. The building block of deep learning.',
    category: 'AI & ML Fundamentals',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Deep Learning', 'Backpropagation', 'Activation Function', 'CNN (Convolutional Neural Network)'],
  },
  {
    term: 'NIST AI RMF',
    definition: 'The NIST AI Risk Management Framework — a voluntary guidance document with four core functions: GOVERN (culture, accountability), MAP (context, risk identification), MEASURE (analysis, assessment), and MANAGE (prioritization, response).',
    category: 'AI Governance',
    certTags: ['SecAI'],
    related: ['EU AI Act', 'ISO 42001', 'AI Risk Management', 'Responsible AI'],
  },
  {
    term: 'NIST SP 800-218A',
    definition: 'NIST Special Publication 800-218A — Secure Software Development Practices for AI/ML-Enabled Software Systems, extending SSDF (SP 800-218) with AI-specific guidance for supply chain, data management, and model security.',
    category: 'AI Governance',
    certTags: ['SecAI', 'CAISP'],
    related: ['NIST AI RMF', 'AI Supply Chain', 'Responsible AI', 'Model Security'],
  },
  {
    term: 'NLP Fundamentals',
    definition: 'Natural Language Processing — the field of AI focused on enabling computers to understand, interpret, and generate human language. Foundational techniques include tokenization, POS tagging, NER, parsing, and text vectorization.',
    category: 'NLP',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Tokenization', 'Named Entity Recognition (NER)', 'Sentiment Analysis', 'BERT'],
  },
  {
    term: 'Non-Maximum Suppression (NMS)',
    definition: 'A post-processing technique in object detection that removes duplicate bounding box predictions by keeping only the highest-confidence detection for each object and suppressing overlapping boxes below an IoU threshold.',
    category: 'Computer Vision',
    certTags: ['IBM-AIE'],
    related: ['Object Detection', 'Intersection over Union (IoU)', 'Anchor Box', 'YOLO'],
  },
  // ── O ─────────────────────────────────────────────────────────────────────
  {
    term: 'Object Detection',
    definition: 'A computer vision task that identifies and localizes multiple objects within an image by predicting bounding boxes and class labels for each detected object. YOLO, Faster R-CNN, and DETR are leading architectures.',
    category: 'Computer Vision',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['CNN (Convolutional Neural Network)', 'Image Classification', 'YOLO', 'Anchor Box'],
  },
  {
    term: 'Optical Character Recognition (OCR)',
    definition: 'Technology that converts images of text (printed, handwritten, or scanned) into machine-readable text. Used in document intelligence, invoice processing, and digitizing historical records.',
    category: 'Computer Vision',
    certTags: ['Azure-AI102'],
    related: ['Computer Vision', 'Image Classification', 'Azure AI Foundry'],
  },
  {
    term: 'Overfitting',
    definition: 'When a model learns the training data too well, including noise and outliers, resulting in poor generalization to new data. Indicated by high training accuracy but low validation/test accuracy. Addressed by regularization, dropout, and more data.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Underfitting', 'Regularization', 'Dropout', 'Cross-Validation'],
  },
  {
    term: 'OWASP LLM Top 10',
    definition: 'The Open Worldwide Application Security Project\'s list of the top 10 security risks for LLM applications (v1.1: LLM01–LLM08). Covers prompt injection, insecure output handling, training data poisoning, excessive agency, and more.',
    category: 'AI Security',
    certTags: ['SecAI', 'CAISP', 'GIAC-GOAA'],
    related: ['LLM01 Prompt Injection', 'LLM08 Excessive Agency', 'Guardrails', 'AI Red Team'],
  },
  // ── P ─────────────────────────────────────────────────────────────────────
  {
    term: 'PEFT (Parameter-Efficient Fine-Tuning)',
    definition: 'Techniques that adapt pre-trained LLMs to new tasks by updating only a small fraction of model parameters, dramatically reducing compute and memory costs compared to full fine-tuning. Includes LoRA, QLoRA, prefix tuning, and adapters.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['LoRA (Low-Rank Adaptation)', 'QLoRA', 'Fine-Tuning', 'Instruction Tuning'],
  },
  {
    term: 'Perplexity',
    definition: 'A measurement of how well a language model predicts a sample of text. Lower perplexity means the model is less "surprised" by the text — it assigned higher probability to the correct tokens. Used to compare language model quality.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE'],
    related: ['Large Language Model (LLM)', 'Tokenization', 'Temperature', 'Loss Function'],
  },
  {
    term: 'Positional Encoding',
    definition: 'A technique for injecting information about token positions into transformer inputs, since self-attention is permutation-invariant. Can be absolute (fixed sinusoidal or learned) or relative (RoPE, ALiBi).',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE'],
    related: ['Transformer', 'Attention Mechanism', 'Tokenization', 'Self-Attention'],
  },
  {
    term: 'Pre-Training',
    definition: 'Training a model from scratch on a large, general dataset to learn broad knowledge and language understanding before task-specific fine-tuning. Foundation models like GPT-4 and Llama are pre-trained on trillions of tokens.',
    category: 'Generative AI & LLMs',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Fine-Tuning', 'Foundation Model', 'Transfer Learning', 'Instruction Tuning'],
  },
  {
    term: 'Precision',
    definition: 'Of all the instances the model predicted as positive, the proportion that were actually positive. Precision = TP / (TP + FP). High precision means few false alarms — important in spam detection and medical diagnosis.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Recall', 'F1 Score', 'Confusion Matrix', 'AUC-ROC'],
  },
  {
    term: 'Principal Component Analysis (PCA)',
    definition: 'A linear dimensionality reduction technique that projects data onto directions of maximum variance (principal components). Used for visualization, noise reduction, and feature extraction as a preprocessing step for ML models.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Dimensionality Reduction', 'Feature Selection', 'Unsupervised Learning', 'Clustering'],
  },
  {
    term: 'Prompt Engineering',
    definition: 'The practice of designing and optimizing prompts (inputs) to LLMs to achieve desired outputs. Techniques include role assignment, few-shot examples, chain-of-thought instructions, and structured output formatting.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Few-Shot Prompting', 'Zero-Shot Prompting', 'Chain-of-Thought Prompting', 'System Prompt'],
  },
  {
    term: 'Prompt Injection',
    definition: 'An attack where adversarial text in user input or retrieved content overrides an LLM\'s instructions, causing it to ignore safety guidelines, leak information, or perform unauthorized actions.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['LLM01 Prompt Injection', 'Indirect Prompt Injection', 'Goal Hijacking', 'Guardrails'],
  },
  {
    term: 'Prompt Leaking',
    definition: 'An attack that extracts an LLM\'s system prompt or confidential instructions by asking the model to repeat, summarize, or translate its instructions. Exposes proprietary prompts that represent business logic or security controls.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA'],
    related: ['System Prompt Extraction', 'LLM06 Sensitive Information Disclosure', 'Jailbreak', 'Prompt Injection'],
  },
  {
    term: 'PyTorch',
    definition: 'An open-source deep learning framework developed by Meta, featuring dynamic computation graphs, intuitive Python API, and strong GPU acceleration. The most popular framework for research and increasingly for production.',
    category: 'Frameworks & Tools',
    certTags: ['IBM-AIE', 'Google-MLE'],
    related: ['TensorFlow', 'CUDA', 'Deep Learning', 'Neural Network'],
  },
  // ── Q ─────────────────────────────────────────────────────────────────────
  {
    term: 'QLoRA',
    definition: 'Quantized LoRA — combines 4-bit quantization of a frozen base model with LoRA adapters. Enables fine-tuning of large models (65B+) on a single consumer GPU by dramatically reducing memory requirements.',
    category: 'Generative AI & LLMs',
    certTags: ['IBM-AIE'],
    related: ['LoRA (Low-Rank Adaptation)', 'PEFT (Parameter-Efficient Fine-Tuning)', 'Quantization', 'Fine-Tuning'],
  },
  {
    term: 'Quantization',
    definition: 'Reducing the numerical precision of model weights (e.g., from 32-bit float to 8-bit or 4-bit integer) to decrease model size and inference latency. Slight accuracy tradeoff for significant speedup and memory savings.',
    category: 'Generative AI & LLMs',
    certTags: ['Google-MLE'],
    related: ['QLoRA', 'Inference', 'Model Serving', 'PEFT (Parameter-Efficient Fine-Tuning)'],
  },
  // ── R ─────────────────────────────────────────────────────────────────────
  {
    term: 'RAG (Retrieval-Augmented Generation)',
    definition: 'An architecture that enhances LLM responses by retrieving relevant documents from a knowledge base and adding them to the prompt context before generation. Reduces hallucination and keeps responses grounded in current, specific data.',
    category: 'Generative AI & LLMs',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI102'],
    related: ['Vector Database', 'Embedding', 'Grounding', 'Hallucination'],
  },
  {
    term: 'RAG Injection',
    definition: 'An indirect prompt injection attack where adversarial content is inserted into a document or knowledge base that the RAG system retrieves, causing the LLM to execute attacker-controlled instructions.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['Indirect Prompt Injection', 'RAG (Retrieval-Augmented Generation)', 'LLM01 Prompt Injection', 'Goal Hijacking'],
  },
  {
    term: 'Random Forest',
    definition: 'An ensemble learning algorithm that trains many decision trees on random subsets of data and features, then averages their predictions. More robust and accurate than a single tree; less prone to overfitting.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Decision Tree', 'Gradient Boosting', 'Ensemble Learning', 'Overfitting'],
  },
  {
    term: 'ReAct Pattern',
    definition: 'Reasoning + Acting — a prompting pattern for AI agents that interleaves reasoning steps ("Thought") with action calls ("Act") and observation of results ("Observe"). Enables structured, auditable multi-step problem solving.',
    category: 'Emerging Trends',
    certTags: ['AWS-AIF-C01'],
    related: ['Agent (AI)', 'Agentic AI', 'Chain-of-Thought Prompting', 'Tool Use'],
  },
  {
    term: 'Recall',
    definition: 'Of all actual positive instances, the proportion the model correctly identified. Recall = TP / (TP + FN). High recall means few missed positives — critical in fraud detection and medical screening.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'Azure-AI900', 'IBM-AIE'],
    related: ['Precision', 'F1 Score', 'Confusion Matrix', 'AUC-ROC'],
  },
  {
    term: 'Red Team (AI)',
    definition: 'A structured effort to probe an AI system for vulnerabilities, biases, and safety failures by adopting an adversarial mindset. AI red teams test prompt injections, jailbreaks, misuse scenarios, and harmful outputs.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA', 'CAISP'],
    related: ['AI Red Team', 'Blue Team', 'Jailbreak', 'Adversarial Attack'],
  },
  {
    term: 'Regularization',
    definition: 'Techniques that reduce overfitting by adding a penalty for model complexity to the loss function. L1 (Lasso) encourages sparsity; L2 (Ridge) penalizes large weights. Dropout is a regularization technique specific to neural networks.',
    category: 'AI & ML Fundamentals',
    certTags: ['IBM-AIE'],
    related: ['Overfitting', 'Dropout', 'Loss Function', 'Cross-Validation'],
  },
  {
    term: 'Reinforcement Learning',
    definition: 'A learning paradigm where an agent learns by interacting with an environment, receiving rewards or penalties for actions, and optimizing a policy to maximize cumulative reward. Used in game AI, robotics, and RLHF.',
    category: 'AI & ML Fundamentals',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['RLHF', 'Supervised Learning', 'Unsupervised Learning', 'Agent (AI)'],
  },
  {
    term: 'ResNet',
    definition: 'Residual Network — a CNN architecture that uses skip connections to allow gradients to flow through very deep networks (50–200+ layers) without vanishing. Revolutionized image classification and remains a standard backbone for CV tasks.',
    category: 'Computer Vision',
    certTags: ['IBM-AIE'],
    related: ['CNN (Convolutional Neural Network)', 'Transfer Learning', 'Image Classification', 'Batch Normalization'],
  },
  {
    term: 'Responsible AI',
    definition: 'A framework and set of practices ensuring AI systems are developed and deployed in ways that are fair, transparent, accountable, safe, and respectful of human rights and privacy.',
    category: 'AI Governance',
    certTags: ['SecAI', 'AWS-AIF-C01', 'Azure-AI900'],
    related: ['Fairness', 'Explainable AI (XAI)', 'NIST AI RMF', 'Model Card'],
  },
  {
    term: 'Retraining Pipeline',
    definition: 'An automated workflow that detects model degradation (via drift monitoring or scheduled triggers), collects new training data, retrains the model, evaluates it against baselines, and redeploys if it meets quality gates.',
    category: 'MLOps',
    certTags: ['Google-MLE'],
    related: ['Model Monitoring', 'Data Drift', 'CI/CD for ML', 'Feature Store'],
  },
  {
    term: 'RLHF (Reinforcement Learning from Human Feedback)',
    definition: 'A fine-tuning technique used to align LLMs with human preferences. Human raters rank model outputs; a reward model is trained on these rankings; the LLM is then fine-tuned with RL to maximize the reward model\'s scores.',
    category: 'Generative AI & LLMs',
    certTags: ['AWS-AIF-C01', 'IBM-AIE'],
    related: ['Fine-Tuning', 'Instruction Tuning', 'Reinforcement Learning', 'Foundation Model'],
  },
  {
    term: 'Role-Play Bypass',
    definition: 'A jailbreak technique that instructs an LLM to adopt a fictional character, persona, or scenario that "doesn\'t have restrictions," using narrative framing to elicit harmful content the model would otherwise refuse.',
    category: 'Red Teaming AI',
    certTags: ['SecAI', 'GIAC-GOAA'],
    related: ['Jailbreak', 'DAN Attack', 'Adversarial Prompt', 'Guardrails'],
  },
];
